# Generated by Django 5.2.6 on 2026-08-30 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0010_billing_inherit_base'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('code', models.CharField(max_length=30, verbose_name='الرمز')),
                ('name_ar', models.CharField(max_length=150, verbose_name='الاسم')),
                ('name_en', models.CharField(blank=True, max_length=150, verbose_name='الاسم بالإنجليزية')),
                ('name_ur', models.CharField(blank=True, max_length=150, verbose_name='الاسم بالأوردو')),
                ('city', models.CharField(blank=True, max_length=80, verbose_name='المدينة')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('mol_establishment_no', models.CharField(blank=True, help_text='إن كان الفرع منشأة مستقلة — يؤثر على احتساب نطاقات', max_length=20, verbose_name='رقم منشأة قوى')),
                ('gosi_establishment_no', models.CharField(blank=True, max_length=20, verbose_name='رقم منشأة التأمينات')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='نشط')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.account', verbose_name='الحساب')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.company', verbose_name='الشركة')),
            ],
            options={
                'verbose_name': 'فرع',
                'verbose_name_plural': 'الفروع',
                'ordering': ['name_ar'],
            },
        ),
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('code', models.CharField(max_length=30, verbose_name='الرمز')),
                ('name_ar', models.CharField(max_length=150, verbose_name='الاسم')),
                ('name_en', models.CharField(blank=True, max_length=150, verbose_name='الاسم بالإنجليزية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.account', verbose_name='الحساب')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.company', verbose_name='الشركة')),
            ],
            options={
                'verbose_name': 'مركز تكلفة',
                'verbose_name_plural': 'مراكز التكلفة',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('code', models.CharField(max_length=30, verbose_name='الرمز')),
                ('name_ar', models.CharField(max_length=150, verbose_name='الاسم')),
                ('name_en', models.CharField(blank=True, max_length=150, verbose_name='الاسم بالإنجليزية')),
                ('name_ur', models.CharField(blank=True, max_length=150, verbose_name='الاسم بالأوردو')),
                ('path', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='المسار')),
                ('depth', models.PositiveSmallIntegerField(default=0, verbose_name='العمق')),
                ('manager_employment_id', models.BigIntegerField(blank=True, help_text='يُربط بنموذج Employment في السبرنت 7', null=True, verbose_name='مدير القسم')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='نشط')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.account', verbose_name='الحساب')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='organization.branch', verbose_name='الفرع')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.company', verbose_name='الشركة')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='organization.department', verbose_name='القسم الأعلى')),
            ],
            options={
                'verbose_name': 'قسم',
                'verbose_name_plural': 'الأقسام',
                'ordering': ['path', 'name_ar'],
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('name_ar', models.CharField(max_length=150, verbose_name='الاسم')),
                ('name_en', models.CharField(blank=True, max_length=150, verbose_name='الاسم بالإنجليزية')),
                ('name_ur', models.CharField(blank=True, max_length=150, verbose_name='الاسم بالأوردو')),
                ('start_date', models.DateField(db_index=True, verbose_name='من')),
                ('end_date', models.DateField(verbose_name='إلى')),
                ('is_paid', models.BooleanField(default=True, verbose_name='مدفوعة')),
                ('note', models.TextField(blank=True, verbose_name='ملاحظة')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.account', verbose_name='الحساب')),
                ('branch', models.ForeignKey(blank=True, help_text='فارغ = كل الشركة', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='organization.branch', verbose_name='الفرع')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.company', verbose_name='الشركة')),
            ],
            options={
                'verbose_name': 'عطلة',
                'verbose_name_plural': 'العطل',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('name_ar', models.CharField(max_length=150, verbose_name='المسمى')),
                ('name_en', models.CharField(blank=True, max_length=150, verbose_name='المسمى بالإنجليزية')),
                ('name_ur', models.CharField(blank=True, max_length=150, verbose_name='المسمى بالأوردو')),
                ('mol_occupation_code', models.CharField(blank=True, db_index=True, help_text='الرمز المعتمد لدى وزارة الموارد البشرية', max_length=20, verbose_name='الرمز المهني')),
                ('is_saudization_reserved', models.BooleanField(default=False, verbose_name='مقصورة على السعوديين')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.account', verbose_name='الحساب')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.company', verbose_name='الشركة')),
            ],
            options={
                'verbose_name': 'مسمى وظيفي',
                'verbose_name_plural': 'المسميات الوظيفية',
                'ordering': ['name_ar'],
            },
        ),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uq_branch_code_per_company'),
        ),
        migrations.AddConstraint(
            model_name='costcenter',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uq_costcenter_code_per_company'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uq_department_code_per_company'),
        ),
        migrations.AddConstraint(
            model_name='holiday',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='chk_holiday_dates'),
        ),
    ]
