# Generated by Django 5.2.6 on 2026-08-29 22:19

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('slug', models.SlugField(help_text='يُستخدم في النطاق الفرعي، مثال: alfahd', max_length=63, unique=True, validators=[django.core.validators.RegexValidator('^[a-z0-9][a-z0-9-]{1,61}[a-z0-9]$', 'المعرّف يقبل حروفًا إنجليزية صغيرة وأرقامًا وشرطات فقط')], verbose_name='المعرّف')),
                ('display_name_ar', models.CharField(max_length=200, verbose_name='اسم المجموعة')),
                ('display_name_en', models.CharField(blank=True, max_length=200, verbose_name='الاسم بالإنجليزية')),
                ('isolation_mode', models.CharField(choices=[('shared', 'مشترك (RLS)'), ('schema', 'سكيما مستقلة'), ('database', 'قاعدة بيانات مستقلة')], default='shared', max_length=20, verbose_name='نمط العزل')),
                ('status', models.CharField(choices=[('trial', 'تجريبي'), ('active', 'نشط'), ('past_due', 'متأخر السداد'), ('grace', 'فترة سماح'), ('suspended', 'موقوف'), ('archived', 'مؤرشف')], db_index=True, default='trial', max_length=20, verbose_name='الحالة')),
                ('default_locale', models.CharField(choices=[('ar', 'العربية'), ('en', 'English'), ('ur', 'اردو')], default='ar', max_length=5, verbose_name='اللغة الافتراضية')),
                ('timezone', models.CharField(default='Asia/Riyadh', max_length=50, verbose_name='المنطقة الزمنية')),
                ('employee_no_scope', models.CharField(choices=[('company', 'على مستوى الشركة'), ('account', 'على مستوى المجموعة')], default='company', max_length=20, verbose_name='نطاق تفرد الرقم الوظيفي')),
                ('allow_cross_company_employment', models.BooleanField(default=True, verbose_name='السماح بالعمل في أكثر من شركة')),
                ('is_sandbox', models.BooleanField(default=False, help_text='الحسابات التجريبية وحدها قابلة للتصفير', verbose_name='حساب تجريبي')),
                ('suspended_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإيقاف')),
                ('suspension_reason', models.TextField(blank=True, verbose_name='سبب الإيقاف')),
            ],
            options={
                'verbose_name': 'حساب',
                'verbose_name_plural': 'الحسابات',
                'ordering': ['display_name_ar'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('code', models.CharField(max_length=30, verbose_name='الرمز')),
                ('legal_name_ar', models.CharField(max_length=255, verbose_name='الاسم النظامي')),
                ('legal_name_en', models.CharField(blank=True, max_length=255, verbose_name='الاسم بالإنجليزية')),
                ('cr_number', models.CharField(blank=True, max_length=20, verbose_name='السجل التجاري')),
                ('cr_expiry_date', models.DateField(blank=True, null=True, verbose_name='انتهاء السجل')),
                ('unified_national_number', models.CharField(blank=True, max_length=20, verbose_name='الرقم الموحّد')),
                ('vat_number', models.CharField(blank=True, max_length=15, verbose_name='الرقم الضريبي')),
                ('gosi_establishment_no', models.CharField(blank=True, max_length=20, verbose_name='رقم منشأة التأمينات')),
                ('mol_establishment_no', models.CharField(blank=True, max_length=20, verbose_name='رقم منشأة قوى')),
                ('activity_code', models.CharField(blank=True, max_length=20, verbose_name='رمز النشاط')),
                ('entity_size', models.CharField(blank=True, max_length=20, verbose_name='حجم المنشأة')),
                ('fiscal_year_start_month', models.PositiveSmallIntegerField(default=1, verbose_name='بداية السنة المالية')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='نشطة')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='accounts.account', verbose_name='الحساب')),
            ],
            options={
                'verbose_name': 'شركة',
                'verbose_name_plural': 'الشركات',
                'ordering': ['legal_name_ar'],
                'constraints': [models.UniqueConstraint(fields=('account', 'code'), name='uq_company_code_per_account')],
            },
        ),
    ]
