# Generated by Django 5.2.6 on 2026-08-30 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_provision_function'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_account_owner', models.BooleanField(default=False, help_text='يتجاوز فحص الصلاحيات داخل حسابه', verbose_name='مالك الحساب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='accounts.account', verbose_name='الحساب')),
                ('active_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.company', verbose_name='الشركة النشطة')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_membership', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'عضوية',
                'verbose_name_plural': 'العضويات',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, verbose_name='الرمز')),
                ('name_ar', models.CharField(max_length=120, verbose_name='الاسم')),
                ('name_en', models.CharField(blank=True, max_length=120, verbose_name='الاسم بالإنجليزية')),
                ('name_ur', models.CharField(blank=True, max_length=120, verbose_name='الاسم بالأوردو')),
                ('default_scope', models.CharField(choices=[('own', 'own'), ('team', 'team'), ('department', 'department'), ('branch', 'branch'), ('company', 'company'), ('account', 'account')], default='own', max_length=20, verbose_name='النطاق الافتراضي')),
                ('is_system', models.BooleanField(default=False, help_text='لا يُحذف ولا تُعدّل صلاحياته الأساسية', verbose_name='دور نظامي')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, help_text='فارغ = دور نظامي مشترك', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='accounts.account', verbose_name='الحساب')),
            ],
            options={
                'verbose_name': 'دور',
                'verbose_name_plural': 'الأدوار',
            },
        ),
        migrations.CreateModel(
            name='RoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('own', 'own'), ('team', 'team'), ('department', 'department'), ('branch', 'branch'), ('company', 'company'), ('account', 'account')], max_length=20, verbose_name='النطاق')),
                ('scope_ref_id', models.BigIntegerField(blank=True, help_text='معرّف الفرع أو القسم عند تضييق النطاق', null=True)),
                ('company', models.ForeignKey(blank=True, help_text='فارغ = يسري على كل شركات الحساب', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.company')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='accounts.accountmembership')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='accounts.role')),
            ],
            options={
                'verbose_name': 'إسناد دور',
                'verbose_name_plural': 'إسنادات الأدوار',
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_key', models.CharField(max_length=80)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='accounts.role')),
            ],
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('account', 'code'), name='uq_role_code_per_account'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(condition=models.Q(('account__isnull', True)), fields=('code',), name='uq_system_role_code'),
        ),
        migrations.AddConstraint(
            model_name='rolepermission',
            constraint=models.UniqueConstraint(fields=('role', 'permission_key'), name='uq_role_permission'),
        ),
    ]
