# Generated by Django 5.2.6 on 2026-08-30 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_fix_lookup_rls'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_key', models.CharField(max_length=60, unique=True, verbose_name='المفتاح')),
                ('module', models.CharField(max_length=40, verbose_name='الوحدة')),
                ('name_ar', models.CharField(max_length=150, verbose_name='الاسم')),
                ('name_en', models.CharField(blank=True, max_length=150, verbose_name='الاسم بالإنجليزية')),
                ('description_ar', models.TextField(blank=True, verbose_name='الوصف')),
                ('value_type', models.CharField(choices=[('bool', 'نعم/لا'), ('int', 'حد رقمي'), ('text', 'نص')], default='bool', max_length=10, verbose_name='نوع القيمة')),
                ('is_core', models.BooleanField(default=False, help_text='متاحة لكل الباقات، لا تُطفأ', verbose_name='ميزة أساسية')),
                ('sort_order', models.IntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'ميزة',
                'verbose_name_plural': 'المزايا',
                'ordering': ['module', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='الرمز')),
                ('name_ar', models.CharField(max_length=120, verbose_name='الاسم')),
                ('name_en', models.CharField(blank=True, max_length=120, verbose_name='الاسم بالإنجليزية')),
                ('tier_order', models.PositiveSmallIntegerField(default=1, help_text='للترقية والتنزيل', verbose_name='المستوى')),
                ('base_fee_monthly', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الرسم الثابت الشهري')),
                ('min_billable_employees', models.PositiveSmallIntegerField(default=1, verbose_name='الحد الأدنى للفوترة')),
                ('max_employees', models.PositiveIntegerField(blank=True, null=True, verbose_name='الحد الأقصى للموظفين')),
                ('trial_days', models.PositiveSmallIntegerField(default=14, verbose_name='أيام التجربة')),
                ('is_public', models.BooleanField(default=True, verbose_name='معروضة للعملاء')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّلة')),
            ],
            options={
                'verbose_name': 'باقة',
                'verbose_name_plural': 'الباقات',
                'ordering': ['tier_order'],
            },
        ),
        migrations.CreateModel(
            name='CompanyHeadcountDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(db_index=True, verbose_name='التاريخ')),
                ('active_employments', models.PositiveIntegerField(default=0, verbose_name='الارتباطات النشطة')),
                ('billable_employments', models.PositiveIntegerField(default=0, verbose_name='المُفوترة')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.account')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headcount_snapshots', to='accounts.company')),
            ],
            options={
                'verbose_name': 'لقطة عدد الموظفين',
                'verbose_name_plural': 'لقطات عدد الموظفين',
                'constraints': [models.UniqueConstraint(fields=('company', 'snapshot_date'), name='uq_headcount_per_day')],
            },
        ),
        migrations.CreateModel(
            name='CompanySubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_cycle', models.CharField(choices=[('monthly', 'شهري'), ('yearly', 'سنوي')], default='monthly', max_length=10, verbose_name='دورة الفوترة')),
                ('status', models.CharField(choices=[('trial', 'تجريبي'), ('active', 'نشط'), ('past_due', 'متأخر السداد'), ('grace', 'فترة سماح'), ('suspended', 'موقوف'), ('cancelled', 'ملغى')], db_index=True, default='trial', max_length=20, verbose_name='الحالة')),
                ('starts_on', models.DateField(verbose_name='تاريخ البدء')),
                ('current_period_start', models.DateField(verbose_name='بداية الفترة الحالية')),
                ('current_period_end', models.DateField(verbose_name='نهاية الفترة الحالية')),
                ('trial_ends_on', models.DateField(blank=True, null=True, verbose_name='انتهاء التجربة')),
                ('grace_ends_on', models.DateField(blank=True, null=True, verbose_name='انتهاء فترة السماح')),
                ('auto_renew', models.BooleanField(default=True, verbose_name='تجديد تلقائي')),
                ('price_override_per_employee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='سعر تفاوضي لكل موظف')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='accounts.account')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='accounts.company')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='accounts.plan')),
            ],
            options={
                'verbose_name': 'اشتراك',
                'verbose_name_plural': 'الاشتراكات',
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['trial', 'active', 'past_due', 'grace'])), fields=('company',), name='uq_active_subscription_per_company')],
            },
        ),
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_key', models.CharField(max_length=60)),
                ('value', models.CharField(default='true', help_text='true أو رقم حدّ', max_length=255)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='accounts.plan')),
            ],
            options={
                'verbose_name': 'ميزة باقة',
                'verbose_name_plural': 'مزايا الباقات',
                'constraints': [models.UniqueConstraint(fields=('plan', 'feature_key'), name='uq_plan_feature')],
            },
        ),
        migrations.CreateModel(
            name='PlanPriceTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_employees', models.PositiveIntegerField(verbose_name='من عدد')),
                ('to_employees', models.PositiveIntegerField(blank=True, help_text='فارغ = فأكثر', null=True, verbose_name='إلى عدد')),
                ('price_per_employee_monthly', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر الشهري لكل موظف')),
                ('price_per_employee_yearly', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='السعر السنوي لكل موظف')),
                ('currency', models.CharField(default='SAR', max_length=3, verbose_name='العملة')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_tiers', to='accounts.plan', verbose_name='الباقة')),
            ],
            options={
                'verbose_name': 'شريحة سعر',
                'verbose_name_plural': 'شرائح الأسعار',
                'ordering': ['plan', 'from_employees'],
                'constraints': [models.UniqueConstraint(fields=('plan', 'from_employees'), name='uq_plan_tier_start')],
            },
        ),
    ]
