# Generated by Django 5.2.6 on 2026-08-31 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_billing_v2_rls'),
        ('employees', '0004_assets_rls'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsubscription',
            name='activated_by_person',
            field=models.ForeignKey(blank=True, help_text='عند التفعيل الإداري بلا دفع إلكتروني', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activated_subscriptions', to='employees.person', verbose_name='فُعّل بواسطة'),
        ),
        migrations.AddField(
            model_name='accountsubscription',
            name='activation_note',
            field=models.TextField(blank=True, help_text='مرجع التحويل البنكي أو سبب التفعيل الإداري', verbose_name='ملاحظة التفعيل'),
        ),
        migrations.AddField(
            model_name='accountsubscription',
            name='grace_until',
            field=models.DateField(blank=True, help_text='يضبطه السوبر أدمن بلا حد — لحالات التحويل البنكي', null=True, verbose_name='تمديد يدوي حتى'),
        ),
        migrations.AddField(
            model_name='accountsubscription',
            name='payment_method',
            field=models.CharField(choices=[('gateway', 'بوابة إلكترونية (ميسر)'), ('bank_transfer', 'تحويل بنكي'), ('manual', 'تفعيل إداري')], default='gateway', help_text='الشركات الكبيرة تفضّل التحويل البنكي', max_length=20, verbose_name='طريقة الدفع'),
        ),
        migrations.AlterField(
            model_name='accountsubscription',
            name='state',
            field=models.CharField(choices=[('trial', 'تجربة مجانية'), ('active', 'نشط'), ('grace', 'مهلة بعد الانتهاء'), ('read_only', 'للقراءة فقط'), ('past_due', 'متأخر السداد'), ('cancelled', 'ملغى')], db_index=True, default='trial', max_length=20, verbose_name='الحالة'),
        ),
    ]
