# Generated by Django 5.2.6 on 2026-08-31 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_subscription_manual_activation'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='total_before_vat',
            field=models.DecimalField(decimal_places=2, default=0, help_text='السعر البارز في صفحة الباقات', max_digits=12, verbose_name='الإجمالي قبل الضريبة'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='قيمة الضريبة'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=15, help_text='تُضبط من لوحة السوبر أدمن', max_digits=5, verbose_name='نسبة الضريبة %'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='المبلغ المشحون من البطاقة', max_digits=12, verbose_name='الإجمالي شامل الضريبة'),
        ),
    ]
