# Generated by Django 5.2.6 on 2026-08-31 10:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_invoice_vat'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('15'), help_text='تغيّرت من 5% إلى 15% في 2020 — قد تتغير مجددًا', max_digits=5, verbose_name='نسبة ضريبة القيمة المضافة %')),
                ('vat_number', models.CharField(blank=True, max_length=20, verbose_name='الرقم الضريبي للمنصة')),
                ('trial_days', models.PositiveSmallIntegerField(default=7, verbose_name='أيام التجربة')),
                ('trial_max_employees', models.PositiveSmallIntegerField(default=5, verbose_name='حد موظفي التجربة')),
                ('grace_days_after_expiry', models.PositiveSmallIntegerField(default=3, help_text='يعمل الحساب فيها ثم يصير للقراءة', verbose_name='مهلة السماح بعد الانتهاء')),
                ('renewal_alert_monthly', models.PositiveSmallIntegerField(default=5, verbose_name='التنبيه قبل (شهري)')),
                ('renewal_alert_annual', models.PositiveSmallIntegerField(default=15, verbose_name='التنبيه قبل (سنوي)')),
                ('invoice_due_days', models.PositiveSmallIntegerField(default=7, verbose_name='مهلة سداد الفاتورة')),
                ('manual_retry_limit', models.PositiveSmallIntegerField(default=3, verbose_name='محاولات الدفع اليدوي')),
                ('manual_retry_cooldown_hours', models.PositiveSmallIntegerField(default=6, verbose_name='مهلة الحظر بعدها (ساعات)')),
                ('auto_retry_hours', models.CharField(default='12,24', help_text='ساعات بين المحاولات — 12,24 يعني بعد 12 ثم بعد 24', max_length=50, verbose_name='جدول إعادة المحاولة التلقائية')),
                ('accounting_api_url', models.CharField(blank=True, max_length=300, verbose_name='رابط محاسبة معتمد')),
                ('accounting_enabled', models.BooleanField(default=False, verbose_name='مزامنة الفواتير مع المحاسبي')),
                ('support_email', models.EmailField(blank=True, max_length=254, verbose_name='بريد الدعم')),
                ('support_mobile', models.CharField(blank=True, max_length=20, verbose_name='جوال الدعم')),
            ],
            options={
                'verbose_name': 'إعدادات المنصة',
                'verbose_name_plural': 'إعدادات المنصة',
            },
        ),
    ]
