# Generated by Django 5.2.6 on 2026-08-31 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_platform_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('username', models.CharField(max_length=60, unique=True, verbose_name='اسم المستخدم')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='البريد')),
                ('full_name', models.CharField(max_length=150, verbose_name='الاسم')),
                ('mobile_e164', models.CharField(blank=True, max_length=20, verbose_name='الجوال')),
                ('password_hash', models.CharField(max_length=256, verbose_name='كلمة المرور')),
                ('role', models.CharField(choices=[('viewer', 'مطّلع — قراءة فقط'), ('support', 'دعم — تفعيل وتمديد'), ('owner', 'مالك المنصة — كل الصلاحيات')], default='viewer', max_length=20, verbose_name='الدور')),
                ('totp_secret', models.CharField(blank=True, max_length=64, verbose_name='سرّ التحقق الثنائي')),
                ('totp_enabled', models.BooleanField(default=False, help_text='إلزامي — الحساب يفتح بيانات كل العملاء', verbose_name='التحقق الثنائي مفعّل')),
                ('allowed_ips', models.TextField(blank=True, help_text='مفصولة بفاصلة — فارغ يعني بلا قيد', verbose_name='عناوين IP المسموحة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('last_login_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر دخول')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='آخر عنوان')),
                ('failed_attempts', models.PositiveSmallIntegerField(default=0, verbose_name='محاولات فاشلة')),
                ('locked_until', models.DateTimeField(blank=True, null=True, verbose_name='مقفل حتى')),
            ],
            options={
                'verbose_name': 'مستخدم منصة',
                'verbose_name_plural': 'مستخدمو المنصة',
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='PlatformSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('token', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='الرمز')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='العنوان')),
                ('user_agent', models.CharField(blank=True, max_length=300, verbose_name='المتصفح')),
                ('expires_at', models.DateTimeField(verbose_name='تنتهي في')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='أُبطلت في')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='accounts.platformuser')),
            ],
            options={
                'verbose_name': 'جلسة منصة',
                'verbose_name_plural': 'جلسات المنصة',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlatformAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('user_name', models.CharField(max_length=150, verbose_name='اسم الفاعل')),
                ('action', models.CharField(db_index=True, max_length=60, verbose_name='العملية')),
                ('target_account_id', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='الحساب المستهدف')),
                ('target_label', models.CharField(blank=True, max_length=200, verbose_name='وصف الهدف')),
                ('detail', models.JSONField(blank=True, default=dict, verbose_name='التفاصيل')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='العنوان')),
                ('success', models.BooleanField(default=True, verbose_name='نجحت')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='accounts.platformuser')),
            ],
            options={
                'verbose_name': 'قيد سجل المنصة',
                'verbose_name_plural': 'سجل عمليات المنصة',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target_account_id', '-created_at'], name='accounts_pl_target__2a3e5a_idx'), models.Index(fields=['user', '-created_at'], name='accounts_pl_user_id_c0c5a2_idx')],
            },
        ),
    ]
