# Generated by Django 5.2.6 on 2026-08-31 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_platform_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpersonationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('account_id', models.PositiveIntegerField(db_index=True, verbose_name='الحساب')),
                ('account_label', models.CharField(max_length=200, verbose_name='اسم الحساب')),
                ('company_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='الشركة')),
                ('as_role', models.CharField(blank=True, help_text='hr_manager · employee — لتشخيص مشاكل الصلاحيات', max_length=40, verbose_name='بدور')),
                ('token', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='الرمز')),
                ('reason', models.CharField(blank=True, max_length=300, verbose_name='سبب الدخول')),
                ('expires_at', models.DateTimeField(verbose_name='تنتهي في')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='انتهت في')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='العنوان')),
                ('writes_count', models.PositiveIntegerField(default=0, verbose_name='عمليات الكتابة')),
                ('platform_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impersonations', to='accounts.platformuser', verbose_name='مستخدم المنصة')),
            ],
            options={
                'verbose_name': 'جلسة انتحال',
                'verbose_name_plural': 'جلسات الانتحال',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['account_id', '-created_at'], name='accounts_im_account_229d4f_idx')],
            },
        ),
    ]
