# Generated by Django 5.2.6 on 2026-08-31 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_impersonation'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='impersonationsession',
            index=models.Index(fields=['platform_user', '-created_at'], name='accounts_im_platfor_efdda0_idx'),
        ),
    ]
