# Generated by Django 5.2.6 on 2026-08-31 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_impersonation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='بصمة الرمز')),
                ('prefix', models.CharField(help_text='أول ثمانية أحرف — للعرض والتمييز فقط', max_length=12, verbose_name='البادئة')),
                ('device_kind', models.CharField(choices=[('web', 'متصفح'), ('ios', 'آيفون'), ('android', 'أندرويد')], default='web', max_length=12, verbose_name='الجهاز')),
                ('device_name', models.CharField(blank=True, max_length=150, verbose_name='اسم الجهاز')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='العنوان')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='ينتهي في')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر استخدام')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='أُبطل في')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'رمز دخول',
                'verbose_name_plural': 'رموز الدخول',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='accounts_au_user_id_4e0bed_idx')],
            },
        ),
    ]
