# Generated by Django 5.2.6 on 2026-09-01 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auth_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='storage_limit_mb',
            field=models.IntegerField(blank=True, help_text='فارغ = بلا حد', null=True, verbose_name='حد التخزين (ميغابايت)'),
        ),
    ]
