# Generated by Django 5.2.6 on 2026-09-01 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_storage_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_key', models.CharField(max_length=60, verbose_name='الصلاحية')),
                ('granted', models.BooleanField(default=True, help_text='صح = تُضاف، خطأ = تُنزع ولو منحها الدور', verbose_name='ممنوحة')),
                ('scope', models.CharField(blank=True, choices=[('own', 'own'), ('team', 'team'), ('department', 'department'), ('branch', 'branch'), ('company', 'company'), ('account', 'account')], help_text='عند المنح — يُهمل عند النزع', max_length=20, verbose_name='النطاق')),
                ('note', models.CharField(blank=True, help_text='لماذا خُصّ هذا الموظف — للمراجعة لاحقًا', max_length=200, verbose_name='سبب الاستثناء')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, help_text='فارغ = يسري على كل شركات الحساب', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.company')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_overrides', to='accounts.accountmembership')),
            ],
            options={
                'verbose_name': 'استثناء صلاحية',
                'verbose_name_plural': 'استثناءات الصلاحيات',
                'constraints': [models.UniqueConstraint(fields=('membership', 'company', 'permission_key'), name='uq_override_per_member_company_perm')],
            },
        ),
    ]
