# Generated by Django 5.2.6 on 2026-09-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_permissionoverride_rls'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmembership',
            name='is_founding_owner',
            field=models.BooleanField(default=False, help_text='أول مالك — لا تُنزع ملكيته إلا بحذفه نهائيًا من الشركة، ويخلفه مالك آخر بنفس الحماية (ق-79)', verbose_name='المالك المؤسس'),
        ),
        migrations.AddField(
            model_name='accountmembership',
            name='owner_since',
            field=models.DateTimeField(blank=True, help_text='ترتيب المنح — به يُعرف من يخلف المؤسس', null=True, verbose_name='مالك منذ'),
        ),
    ]
