# Generated by Django 5.2.6 on 2026-09-04 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_accountmembership_is_founding_owner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApproverScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(help_text='رمز النوع كما في كتالوج الطلبات', max_length=30, verbose_name='نوع الطلب')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='ملاحظة')),
                ('created_by_person_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.account', verbose_name='الحساب')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.company', verbose_name='الشركة')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approver_scopes', to='accounts.accountmembership', verbose_name='العضوية')),
            ],
            options={
                'verbose_name': 'تخصيص اعتماد',
                'verbose_name_plural': 'تخصيصات الاعتماد',
                'indexes': [models.Index(fields=['company', 'request_type'], name='accounts_ap_company_08bc6d_idx')],
                'constraints': [models.UniqueConstraint(fields=('membership', 'company', 'request_type'), name='uq_approver_scope')],
            },
        ),
    ]
