# Generated by Django 5.2.6 on 2026-09-08 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_drop_border_from_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='يصله ردّ الموظفين على رسائل النظام', max_length=254, verbose_name='بريد التواصل'),
        ),
    ]
