# Generated by Django 5.2.6 on 2026-09-08 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_provision_contact_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('company_id', models.BigIntegerField(db_index=True, verbose_name='الشركة')),
                ('person_id', models.BigIntegerField(db_index=True, verbose_name='الشخص')),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='بصمة الرمز')),
                ('status', models.CharField(choices=[('pending', 'بانتظار القبول'), ('accepted', 'قُبلت'), ('revoked', 'أُلغيت')], db_index=True, default='pending', max_length=20, verbose_name='الحالة')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='تنتهي في')),
                ('sent_to_email', models.EmailField(blank=True, max_length=254, verbose_name='أُرسلت إلى')),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('invited_by_person_id', models.BigIntegerField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_user_id', models.BigIntegerField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.account', verbose_name='الحساب')),
            ],
            options={
                'verbose_name': 'دعوة انضمام',
                'verbose_name_plural': 'دعوات الانضمام',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['person_id', 'status'], name='idx_invite_person_status')],
            },
        ),
    ]
