# Generated by Django 5.2.6 on 2026-09-08 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_platform_accounts_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsubscription',
            name='subscribed_employees',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد الموظفين المشترَك به'),
        ),
    ]
