# Generated by Django 5.2.6 on 2026-09-08 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_subscribed_employees'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='setup_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='يُدفع مرّة واحدة — ولا يدخل التجديد', max_digits=10, verbose_name='رسم الإعداد الأوّليّ'),
        ),
    ]
