# Generated by Django 5.2.6 on 2026-09-09 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_invoice_account_lookup'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='additional_number',
            field=models.CharField(blank=True, max_length=10, verbose_name='الرقم الإضافي'),
        ),
        migrations.AddField(
            model_name='company',
            name='building_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='رقم المبنى'),
        ),
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='المدينة'),
        ),
        migrations.AddField(
            model_name='company',
            name='district',
            field=models.CharField(blank=True, max_length=100, verbose_name='الحي'),
        ),
        migrations.AddField(
            model_name='company',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='الرمز البريدي'),
        ),
        migrations.AddField(
            model_name='company',
            name='street',
            field=models.CharField(blank=True, max_length=255, verbose_name='الشارع'),
        ),
    ]
