# Generated by Django 5.2.6 on 2026-09-09 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_provision_national_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_overage',
            field=models.BooleanField(default=False, verbose_name='فاتورة فرق'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='overage_employees',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد الموظفين المضافين'),
        ),
    ]
