# Generated by Django 5.2.6 on 2026-09-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_invoice_seq'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('user_id', models.BigIntegerField(db_index=True, verbose_name='المستخدم')),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='بصمة الرمز')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='ينتهي في')),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'استعادة كلمة مرور',
                'verbose_name_plural': 'طلبات الاستعادة',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SignupRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('company_name', models.CharField(max_length=150, verbose_name='اسم الشركة')),
                ('full_name', models.CharField(max_length=150, verbose_name='اسم المسؤول')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='البريد')),
                ('mobile', models.CharField(blank=True, max_length=20, verbose_name='الجوال')),
                ('password_hash', models.CharField(max_length=256, verbose_name='كلمة المرور')),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='بصمة الرمز')),
                ('status', models.CharField(choices=[('pending', 'بانتظار تأكيد البريد'), ('verified', 'مؤكَّد — أُنشئ الحساب'), ('expired', 'منتهٍ')], db_index=True, default='pending', max_length=20, verbose_name='الحالة')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='ينتهي في')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_account_id', models.BigIntegerField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'طلب تسجيل',
                'verbose_name_plural': 'طلبات التسجيل',
                'ordering': ['-created_at'],
            },
        ),
    ]
