# Generated by Django 5.2.6 on 2026-09-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_signup_and_reset'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmembership',
            name='login_mobile',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name='جوال الدخول'),
        ),
    ]
