# Generated by Django 5.2.6 on 2026-09-09 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_lookup_login_mobile'),
        ('employees', '0013_alter_employment_allow_mobile_punch'),
    ]

    operations = [
        migrations.AddField(
            model_name='roleassignment',
            name='employment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='employees.employment', verbose_name='التوظيف'),
        ),
    ]
