# Generated by Django 5.2.6 on 2026-09-09 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_plan_platform_write'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='guarded_at',
            field=models.CharField(blank=True, help_text='المسار أو الخدمة التي تفحصها — للتوثيق', max_length=255, verbose_name='موضع الحراسة'),
        ),
        migrations.AddField(
            model_name='feature',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='مفعّلة'),
        ),
        migrations.AddField(
            model_name='feature',
            name='is_implemented',
            field=models.BooleanField(default=False, help_text='غير المبنيّة لا تظهر في الباقات ولا تُباع', verbose_name='مبنيّة في النظام'),
        ),
    ]
