# Generated by Django 5.2.6 on 2026-09-14 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_builtin_roles_are_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='dept_manager_permissions',
            field=models.JSONField(blank=True, default=list, help_text='فارغ = الافتراض', verbose_name='صلاحيات مدير الإدارة'),
        ),
    ]
