# Generated by Django 5.2.6 on 2026-09-14 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0054_dept_perms_db_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='dept_manager_permissions',
        ),
    ]
