# Generated by Django 5.2.6 on 2026-09-14 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0055_drop_dept_perms'),
        ('core', '0020_api_keys_rls'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_logos', to='core.storedfile', verbose_name='شعار الشركة'),
        ),
    ]
