# Generated by Django 5.2.6 on 2026-09-15 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0057_logo_db_default'),
        ('core', '0020_api_keys_rls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='zatca_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zatca_invoices', to='core.storedfile', verbose_name='نسخة الفاتورة'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='zatca_invoice_no',
            field=models.CharField(blank=True, max_length=60, verbose_name='رقم الفاتورة الزكاتية'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='zatca_issued_at',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ إصدارها'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='zatca_recorded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت التسجيل'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='zatca_recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_zatca_invoices', to=settings.AUTH_USER_MODEL, verbose_name='سجّلها'),
        ),
    ]
