# Generated by Django 5.2.6 on 2026-09-28 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0064_invite_existing_free_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='bank_beneficiary',
            field=models.CharField(blank=True, max_length=150, verbose_name='اسم المستفيد'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='bank_iban',
            field=models.CharField(blank=True, max_length=34, verbose_name='الآيبان'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='bank_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='اسم البنك'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='bank_transfer_enabled',
            field=models.BooleanField(default=False, verbose_name='إتاحة التحويل البنكي'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='notify_email',
            field=models.EmailField(blank=True, help_text='يصله كل تسجيلٍ جديد وكل طلب تحويلٍ بنكيّ', max_length=254, verbose_name='بريد إشعارات المنصّة'),
        ),
    ]
