# Generated by Django 5.2.6 on 2026-09-28 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0065_platform_notify_and_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='gateway_enabled',
            field=models.BooleanField(default=True, verbose_name='إتاحة الدفع بالبطاقة'),
        ),
    ]
