# Generated by Django 5.2.6 on 2026-09-28 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0066_gateway_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='promo_code',
            field=models.CharField(blank=True, help_text='يُعرض للنسخ — ويجب أن يكون كودًا قائمًا في الخصومات', max_length=40, verbose_name='كود العرض'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='promo_enabled',
            field=models.BooleanField(default=False, verbose_name='إظهار شريط العرض'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='promo_text',
            field=models.CharField(blank=True, help_text='مثال: خصم ٢٠٪ على الاشتراك السنوي', max_length=160, verbose_name='نصّ العرض'),
        ),
    ]
