# Generated by Django 5.2.6 on 2026-09-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0067_promo_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='audience',
            field=models.CharField(choices=[('all', 'جميع العملاء'), ('new', 'العملاء الجدد'), ('renewal', 'عملاء التجديد')], default='all', max_length=20, verbose_name='الفئة المستهدفة'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='scope',
            field=models.CharField(choices=[('one_time', 'مرة واحدة على فاتورة'), ('recurring', 'سعر خاص يستمر مع التجديد'), ('coupon', 'كود خصم يُدخله العميل'), ('campaign', 'حملة عامة (بلا كود)')], max_length=20, verbose_name='النطاق'),
        ),
    ]
