# Generated by Django 5.2.6 on 2026-09-28 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0068_discount_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='stackable',
            field=models.BooleanField(default=False, help_text='إن كان مطفأً فالأعلى قيمةً وحده يُطبَّق', verbose_name='يُجمع مع كود الخصم'),
        ),
    ]
