# Generated by Django 5.2.6 on 2026-08-30 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0010_billing_inherit_base'),
        ('employees', '0002_employees_rls'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('code', models.CharField(max_length=40, verbose_name='الرمز')),
                ('name_ar', models.CharField(max_length=120, verbose_name='الاسم')),
                ('name_en', models.CharField(blank=True, max_length=120, verbose_name='الاسم بالإنجليزية')),
                ('name_ur', models.CharField(blank=True, max_length=120, verbose_name='الاسم بالأوردو')),
                ('is_paid', models.BooleanField(default=True, help_text='غير المدفوعة: لا تُحتسب غيابًا لكن يُخصم أجر اليوم', verbose_name='مدفوعة')),
                ('pay_percentage', models.DecimalField(decimal_places=2, default=100, help_text='للإجازات متدرجة الأجر مثل المرضية', max_digits=5, verbose_name='نسبة الأجر')),
                ('accrual_method', models.CharField(choices=[('monthly', 'شهري بالتناسب'), ('annual', 'دفعة سنوية'), ('per_event', 'لكل واقعة'), ('none', 'بلا استحقاق تلقائي')], default='annual', max_length=20, verbose_name='طريقة الاستحقاق')),
                ('days_per_year', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='الأيام السنوية')),
                ('days_after_five_years', models.DecimalField(blank=True, decimal_places=2, help_text='السنوية ترتفع من 21 إلى 30 بعد 5 سنوات خدمة', max_digits=6, null=True, verbose_name='الأيام بعد 5 سنوات')),
                ('days_per_event', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='أيام الواقعة')),
                ('carry_forward_policy', models.CharField(choices=[('full', 'يُرحَّل كاملًا'), ('capped', 'يُرحَّل بحد أقصى'), ('expire', 'يسقط ما لم يُستخدم')], default='full', max_length=20, verbose_name='سياسة الترحيل')),
                ('max_carry_forward_days', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='الحد الأقصى للترحيل')),
                ('holiday_treatment', models.CharField(choices=[('counted', 'تُحتسب من الرصيد'), ('extends', 'تُمدَّد الإجازة بعددها')], default='counted', max_length=20, verbose_name='العطل داخل الإجازة')),
                ('weekend_treatment', models.CharField(choices=[('counted', 'تُحتسب من الرصيد'), ('extends', 'تُمدَّد الإجازة بعددها')], default='counted', max_length=20, verbose_name='الراحة الأسبوعية داخل الإجازة')),
                ('gender_restriction', models.CharField(choices=[('any', 'الجميع'), ('male', 'ذكور فقط'), ('female', 'إناث فقط')], default='any', max_length=10, verbose_name='قيد الجنس')),
                ('muslim_only', models.BooleanField(default=False, help_text='مثل إجازة الحج', verbose_name='للمسلمين فقط')),
                ('min_service_months', models.PositiveSmallIntegerField(default=0, verbose_name='أقل مدة خدمة (أشهر)')),
                ('once_per_service', models.BooleanField(default=False, verbose_name='مرة واحدة طوال الخدمة')),
                ('requires_attachment', models.BooleanField(default=False, verbose_name='يتطلب مرفقًا')),
                ('max_consecutive_days', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='أقصى مدة متصلة')),
                ('is_system', models.BooleanField(default=False, verbose_name='نوع نظامي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('display_order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.account', verbose_name='الحساب')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.company', verbose_name='الشركة')),
            ],
            options={
                'verbose_name': 'نوع إجازة',
                'verbose_name_plural': 'أنواع الإجازات',
                'ordering': ['display_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='LeaveTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_day', models.PositiveSmallIntegerField(verbose_name='من اليوم')),
                ('to_day', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='إلى اليوم')),
                ('pay_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='نسبة الأجر')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='leaves.leavetype')),
            ],
            options={
                'verbose_name': 'شريحة إجازة',
                'verbose_name_plural': 'شرائح الإجازات',
                'ordering': ['leave_type', 'from_day'],
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('year', models.PositiveSmallIntegerField(verbose_name='السنة')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='الرصيد الافتتاحي')),
                ('accrued', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='المستحق')),
                ('consumed', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='المستهلك')),
                ('adjusted', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='التسويات')),
                ('carried_forward', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='المُرحَّل للسنة التالية')),
                ('last_accrual_date', models.DateField(blank=True, null=True, verbose_name='آخر استحقاق')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.account', verbose_name='الحساب')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.company', verbose_name='الشركة')),
                ('employment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='employees.employment', verbose_name='الموظف')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balances', to='leaves.leavetype')),
            ],
            options={
                'verbose_name': 'رصيد إجازة',
                'verbose_name_plural': 'أرصدة الإجازات',
            },
        ),
        migrations.AddConstraint(
            model_name='leavetype',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uq_leavetype_code_per_company'),
        ),
        migrations.AddConstraint(
            model_name='leavetier',
            constraint=models.UniqueConstraint(fields=('leave_type', 'from_day'), name='uq_leave_tier_start'),
        ),
        migrations.AddConstraint(
            model_name='leavebalance',
            constraint=models.UniqueConstraint(fields=('employment', 'leave_type', 'year'), name='uq_leave_balance'),
        ),
    ]
