# Generated by Django 5.2.6 on 2026-08-30 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_billing_inherit_base'),
        ('employees', '0002_employees_rls'),
        ('leaves', '0001_leave_and_request_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='statutory_min_days',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='السنوية 21، والحج 10 — يُمنع النزول عنه', max_digits=6, null=True, verbose_name='الحد النظامي الأدنى'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='days_per_year',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='يُستخدم عند غياب استحقاق فردي للموظف (ق-33)', max_digits=6, null=True, verbose_name='الأيام السنوية (افتراضي)'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='holiday_treatment',
            field=models.CharField(choices=[('counted', 'تُحتسب من الرصيد'), ('extends', 'تُمدَّد الإجازة بعددها')], default='extends', help_text='الافتراض: العطل تُمدّد الإجازة ولا تُخصم من الرصيد', max_length=20, verbose_name='العطل داخل الإجازة'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='weekend_treatment',
            field=models.CharField(choices=[('counted', 'تُحتسب من الرصيد'), ('extends', 'تُمدَّد الإجازة بعددها')], default='counted', help_text='الافتراض: الراحة الأسبوعية تُحتسب من الرصيد', max_length=20, verbose_name='الراحة الأسبوعية داخل الإجازة'),
        ),
        migrations.CreateModel(
            name='ApprovalChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('request_type', models.CharField(choices=[('leave', 'إجازة'), ('advance', 'سلفة'), ('ticket', 'تذكرة سفر'), ('asset', 'عهدة'), ('permission', 'استئذان'), ('certificate', 'شهادة أو خطاب'), ('resignation', 'استقالة'), ('overtime', 'عمل إضافي'), ('attendance_fix', 'تصحيح بصمة')], db_index=True, max_length=40, verbose_name='نوع الطلب')),
                ('name_ar', models.CharField(max_length=120, verbose_name='اسم السلسلة')),
                ('condition_json', models.JSONField(blank=True, default=dict, help_text='مثال: {"days_gt": 5} أو {"amount_gt": 5000}', verbose_name='الشرط')),
                ('priority', models.IntegerField(default=0, help_text='الأعلى يُفحص أولًا — للسلاسل المشروطة', verbose_name='الأولوية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.account', verbose_name='الحساب')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.company', verbose_name='الشركة')),
            ],
            options={
                'verbose_name': 'سلسلة اعتماد',
                'verbose_name_plural': 'سلاسل الاعتماد',
                'ordering': ['request_type', '-priority'],
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('request_no', models.CharField(max_length=30, verbose_name='رقم الطلب')),
                ('request_type', models.CharField(choices=[('leave', 'إجازة'), ('advance', 'سلفة'), ('ticket', 'تذكرة سفر'), ('asset', 'عهدة'), ('permission', 'استئذان'), ('certificate', 'شهادة أو خطاب'), ('resignation', 'استقالة'), ('overtime', 'عمل إضافي'), ('attendance_fix', 'تصحيح بصمة')], db_index=True, max_length=40, verbose_name='النوع')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('pending', 'قيد الاعتماد'), ('approved', 'معتمد'), ('rejected', 'مرفوض'), ('cancelled', 'ملغى'), ('withdrawn', 'مسحوب')], db_index=True, default='draft', max_length=20, verbose_name='الحالة')),
                ('payload', models.JSONField(default=dict, verbose_name='تفاصيل الطلب')),
                ('note', models.TextField(blank=True, verbose_name='ملاحظة مقدّم الطلب')),
                ('attachment_url', models.CharField(blank=True, max_length=500, verbose_name='المرفق')),
                ('channel', models.CharField(choices=[('web', 'المتصفح'), ('mobile', 'الجوال'), ('whatsapp', 'واتساب')], default='web', max_length=20, verbose_name='قناة التقديم')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت التقديم')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الإغلاق')),
                ('current_step', models.PositiveSmallIntegerField(default=0, verbose_name='درجة الاعتماد الحالية')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.account', verbose_name='الحساب')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.company', verbose_name='الشركة')),
                ('employment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='employees.employment', verbose_name='مقدّم الطلب')),
            ],
            options={
                'verbose_name': 'طلب',
                'verbose_name_plural': 'الطلبات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('step_order', models.PositiveSmallIntegerField(verbose_name='الدرجة')),
                ('decision', models.CharField(blank=True, choices=[('approved', 'معتمد'), ('rejected', 'مرفوض'), ('delegated', 'مُحوَّل')], max_length=20, verbose_name='القرار')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت القرار')),
                ('comment', models.TextField(blank=True, verbose_name='التعليق')),
                ('acted_via', models.CharField(default='web', max_length=20, verbose_name='القناة')),
                ('due_at', models.DateTimeField(blank=True, null=True, verbose_name='موعد الاستحقاق')),
                ('escalated', models.BooleanField(default=False, verbose_name='صُعِّد')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.account', verbose_name='الحساب')),
                ('approver_employment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approvals_given', to='employees.employment', verbose_name='المعتمِد')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.company', verbose_name='الشركة')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='leaves.request')),
            ],
            options={
                'verbose_name': 'اعتماد طلب',
                'verbose_name_plural': 'اعتمادات الطلبات',
                'ordering': ['request', 'step_order'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_order', models.PositiveSmallIntegerField(verbose_name='الترتيب')),
                ('approver_type', models.CharField(choices=[('direct_manager', 'المدير المباشر'), ('department_head', 'مدير الإدارة'), ('role', 'دور محدد'), ('specific_person', 'شخص محدد')], max_length=30, verbose_name='نوع المعتمِد')),
                ('approver_role_code', models.CharField(blank=True, help_text='عند approver_type=role', max_length=40, verbose_name='رمز الدور')),
                ('is_mandatory', models.BooleanField(default=True, verbose_name='إلزامية')),
                ('sla_hours', models.PositiveSmallIntegerField(blank=True, help_text='التجاوز يُطلق حدث تصعيد', null=True, verbose_name='مهلة الاعتماد (ساعات)')),
                ('approver_person', models.ForeignKey(blank=True, help_text='عند approver_type=specific_person', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='employees.person')),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='leaves.approvalchain')),
            ],
            options={
                'verbose_name': 'درجة اعتماد',
                'verbose_name_plural': 'درجات الاعتماد',
                'ordering': ['chain', 'step_order'],
                'constraints': [models.UniqueConstraint(fields=('chain', 'step_order'), name='uq_approval_step_order')],
            },
        ),
        migrations.CreateModel(
            name='LeaveEntitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('days_per_year', models.DecimalField(decimal_places=2, help_text='أي رقم حسب العقد. يُمنع النزول عن الحد النظامي', max_digits=6, verbose_name='الأيام السنوية')),
                ('effective_from', models.DateField(verbose_name='سريان من')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='سريان إلى')),
                ('note', models.TextField(blank=True, help_text='مرجع بند العقد مثلًا', verbose_name='ملاحظة')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.account', verbose_name='الحساب')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.company', verbose_name='الشركة')),
                ('employment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_entitlements', to='employees.employment', verbose_name='الموظف')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entitlements', to='leaves.leavetype')),
            ],
            options={
                'verbose_name': 'استحقاق إجازة',
                'verbose_name_plural': 'استحقاقات الإجازات',
                'ordering': ['-effective_from'],
                'constraints': [models.UniqueConstraint(fields=('employment', 'leave_type', 'effective_from'), name='uq_leave_entitlement'), models.CheckConstraint(condition=models.Q(('days_per_year__gt', 0)), name='chk_entitlement_positive')],
            },
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['company', 'status', 'request_type'], name='leaves_requ_company_153f28_idx'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['employment', '-created_at'], name='leaves_requ_employm_8e14d5_idx'),
        ),
        migrations.AddConstraint(
            model_name='request',
            constraint=models.UniqueConstraint(fields=('company', 'request_no'), name='uq_request_no_per_company'),
        ),
        migrations.AddConstraint(
            model_name='requestapproval',
            constraint=models.UniqueConstraint(fields=('request', 'step_order', 'approver_employment'), name='uq_approval_per_step_approver'),
        ),
    ]
