# Generated by Django 5.2.6 on 2026-09-01 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0004_request_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalchain',
            name='request_type',
            field=models.CharField(choices=[('leave', 'إجازة'), ('advance', 'سلفة'), ('ticket', 'تذكرة سفر'), ('asset', 'عهدة'), ('permission', 'استئذان'), ('certificate', 'شهادة أو خطاب'), ('resignation', 'استقالة'), ('overtime', 'عمل إضافي'), ('attendance_fix', 'تصحيح بصمة'), ('remote_work', 'عمل عن بُعد'), ('business_trip', 'رحلة عمل'), ('profile_update', 'تعديل بيانات')], db_index=True, max_length=40, verbose_name='نوع الطلب'),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_type',
            field=models.CharField(choices=[('leave', 'إجازة'), ('advance', 'سلفة'), ('ticket', 'تذكرة سفر'), ('asset', 'عهدة'), ('permission', 'استئذان'), ('certificate', 'شهادة أو خطاب'), ('resignation', 'استقالة'), ('overtime', 'عمل إضافي'), ('attendance_fix', 'تصحيح بصمة'), ('remote_work', 'عمل عن بُعد'), ('business_trip', 'رحلة عمل'), ('profile_update', 'تعديل بيانات')], db_index=True, max_length=40, verbose_name='النوع'),
        ),
    ]
