# Generated by Django 5.2.6 on 2026-09-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0005_profile_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalstep',
            name='is_acknowledgement',
            field=models.BooleanField(default=False, help_text='علم لا موافقة: زر «اطّلعت» وحده، والجميع يؤكّد قبل أن تمضي السلسلة (ق-74)', verbose_name='درجة علم'),
        ),
    ]
