# Generated by Django 5.2.6 on 2026-09-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0006_approvalstep_is_acknowledgement'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalstep',
            name='same_department',
            field=models.BooleanField(default=False, help_text='يحصر المعتمِدين في إدارة مقدّم الطلب — فمشرفو إدارة أخرى لا شأن لهم بغيابه', verbose_name='ضمن نفس الإدارة'),
        ),
    ]
