# Generated by Django 5.2.6 on 2026-09-02 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_permissionoverride_rls'),
        ('employees', '0006_profile_rls'),
        ('leaves', '0007_approvalstep_same_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delegation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('starts_on', models.DateField(verbose_name='من')),
                ('ends_on', models.DateField(verbose_name='إلى')),
                ('status', models.CharField(choices=[('pending', 'بانتظار قبول النائب'), ('accepted', 'مقبولة'), ('declined', 'مرفوضة')], db_index=True, default='pending', max_length=20, verbose_name='الحالة')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت القرار')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='ملاحظة')),
                ('absentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations_given', to='employees.employment', verbose_name='الغائب')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.account', verbose_name='الحساب')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.company', verbose_name='الشركة')),
                ('deputy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations_received', to='employees.employment', verbose_name='النائب')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delegation', to='leaves.request', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'إنابة',
                'verbose_name_plural': 'الإنابات',
                'indexes': [models.Index(fields=['deputy', 'status'], name='leaves_dele_deputy__66affc_idx'), models.Index(fields=['absentee', 'starts_on', 'ends_on'], name='leaves_dele_absente_17a470_idx')],
            },
        ),
    ]
