# Generated by Django 5.2.6 on 2026-09-04 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0009_delegation_rls'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegation',
            name='is_permanent',
            field=models.BooleanField(default=False, help_text='بديل من غادر موقعه — لا يُنتظر انتهاؤها (ق-79). والإنابة المؤقتة تنتهي بتاريخها (ق-75)', verbose_name='خلافة دائمة'),
        ),
        migrations.AlterField(
            model_name='delegation',
            name='ends_on',
            field=models.DateField(blank=True, null=True, verbose_name='إلى'),
        ),
    ]
