# Generated by Django 5.2.6 on 2026-09-04 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0010_delegation_is_permanent_alter_delegation_ends_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegation',
            name='request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delegation', to='leaves.request', verbose_name='الطلب'),
        ),
    ]
