# Generated by Django 5.2.6 on 2026-09-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0011_alter_delegation_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalstep',
            name='escalate_after_hours',
            field=models.PositiveIntegerField(default=0, help_text='صفر = لا تصعيد. ولا يُتجاوز مدير الموارد ولا المدير العام ولا آخر درجة', verbose_name='التصعيد بعد (ساعة)'),
        ),
    ]
