# Generated by Django 5.2.6 on 2026-09-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0013_exemption_and_default_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalchain',
            name='request_type',
            field=models.CharField(choices=[('leave', 'إجازة'), ('advance', 'سلفة'), ('ticket', 'تذكرة سفر'), ('asset', 'عهدة'), ('permission', 'استئذان'), ('certificate', 'شهادة أو خطاب'), ('resignation', 'استقالة'), ('overtime', 'عمل إضافي'), ('attendance_fix', 'تصحيح بصمة'), ('remote_work', 'عمل عن بُعد'), ('business_trip', 'رحلة عمل'), ('profile_update', 'تعديل بيانات'), ('attendance_exemption', 'إعفاء من البصمة'), ('swap_restday', 'تبديل يوم راحة'), ('custom_payment', 'صرف مخصّص'), ('grievance', 'تظلّم'), ('offsite', 'دوام خارج المكتب'), ('purchase', 'مشتريات'), ('shift_change', 'تغيير فترة عمل'), ('salary_fix', 'تثبيت الراتب')], db_index=True, max_length=40, verbose_name='نوع الطلب'),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_type',
            field=models.CharField(choices=[('leave', 'إجازة'), ('advance', 'سلفة'), ('ticket', 'تذكرة سفر'), ('asset', 'عهدة'), ('permission', 'استئذان'), ('certificate', 'شهادة أو خطاب'), ('resignation', 'استقالة'), ('overtime', 'عمل إضافي'), ('attendance_fix', 'تصحيح بصمة'), ('remote_work', 'عمل عن بُعد'), ('business_trip', 'رحلة عمل'), ('profile_update', 'تعديل بيانات'), ('attendance_exemption', 'إعفاء من البصمة'), ('swap_restday', 'تبديل يوم راحة'), ('custom_payment', 'صرف مخصّص'), ('grievance', 'تظلّم'), ('offsite', 'دوام خارج المكتب'), ('purchase', 'مشتريات'), ('shift_change', 'تغيير فترة عمل'), ('salary_fix', 'تثبيت الراتب')], db_index=True, max_length=40, verbose_name='النوع'),
        ),
    ]
