# Generated by Django 5.2.6 on 2026-09-12 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_builtin_roles_are_system'),
        ('leaves', '0014_seven_request_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomRequestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('code', models.CharField(max_length=40, verbose_name='الرمز')),
                ('name_ar', models.CharField(max_length=120, verbose_name='اسم الطلب')),
                ('name_en', models.CharField(blank=True, max_length=120, verbose_name='بالإنجليزية')),
                ('hint_ar', models.CharField(blank=True, max_length=255, verbose_name='التوضيح')),
                ('icon', models.CharField(blank=True, max_length=30)),
                ('requires_attachment', models.BooleanField(default=False, verbose_name='يلزمه مرفق')),
                ('daily_unique', models.BooleanField(default=False, help_text='يمنع طلبين في يومٍ واحد — إلا إن رُفض الأول', verbose_name='مرّة واحدة في اليوم')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.account', verbose_name='الحساب')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.company', verbose_name='الشركة')),
            ],
            options={
                'verbose_name': 'نوع طلب مخصّص',
                'verbose_name_plural': 'أنواع الطلبات المخصّصة',
                'ordering': ['sort_order', 'name_ar'],
            },
        ),
        migrations.CreateModel(
            name='CustomRequestField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('key', models.CharField(help_text='بالإنجليزية بلا مسافات — يُحفظ به في الطلب', max_length=40, verbose_name='المفتاح')),
                ('label_ar', models.CharField(max_length=120, verbose_name='التسمية')),
                ('kind', models.CharField(choices=[('text', 'نصّ قصير'), ('textarea', 'نصّ طويل'), ('number', 'رقم'), ('date', 'تاريخ'), ('time', 'وقت'), ('bool', 'نعم / لا'), ('select', 'اختيار من قائمة'), ('attachment', 'مرفق')], default='text', max_length=15, verbose_name='النوع')),
                ('is_required', models.BooleanField(default=True, verbose_name='إلزاميّ')),
                ('options', models.CharField(blank=True, help_text='للاختيار من قائمة — مفصولةٌ بفواصل', max_length=500, verbose_name='الخيارات')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.account', verbose_name='الحساب')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.company', verbose_name='الشركة')),
                ('request_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='leaves.customrequesttype', verbose_name='النوع')),
            ],
            options={
                'verbose_name': 'حقل طلب مخصّص',
                'verbose_name_plural': 'حقول الطلبات المخصّصة',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='customrequesttype',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uq_customreqtype_company_code'),
        ),
        migrations.AddConstraint(
            model_name='customrequestfield',
            constraint=models.UniqueConstraint(fields=('request_type', 'key'), name='uq_customreqfield_type_key'),
        ),
    ]
