# Generated by Django 5.2.6 on 2026-09-14 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0017_custom_request_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='accrual_basis_days',
            field=models.PositiveSmallIntegerField(default=365, help_text='٣٦٥ للتقويم · أو أيام العمل السنوية', verbose_name='أساس الأيام للاستحقاق'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='waiting_period_days',
            field=models.PositiveSmallIntegerField(default=0, help_text='٠ = من أول يوم', verbose_name='مدّة الانتظار قبل الاستهلاك (يومًا)'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='accrual_method',
            field=models.CharField(choices=[('daily', 'يومي بالتناسب'), ('monthly', 'شهري بالتناسب'), ('annual', 'دفعة سنوية'), ('per_event', 'لكل واقعة'), ('none', 'بلا استحقاق تلقائي')], default='annual', max_length=20, verbose_name='طريقة الاستحقاق'),
        ),
    ]
