# Generated by Django 5.2.6 on 2026-09-14 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0018_daily_accrual'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='is_contractual',
            field=models.BooleanField(default=False, help_text='يظهر في عقد الموظف ويُخصَّص له', verbose_name='رصيدٌ تعاقديّ'),
        ),
    ]
