# Generated by Django 5.2.6 on 2026-08-30 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0010_billing_inherit_base'),
        ('core', '0001_rls_helpers'),
        ('employees', '0004_assets_rls'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('object_type', models.CharField(db_index=True, help_text='employment · payslip · advance · leave_request …', max_length=60, verbose_name='نوع السجل')),
                ('object_id', models.PositiveIntegerField(db_index=True, verbose_name='معرّف السجل')),
                ('object_label', models.CharField(blank=True, help_text='يُحفظ لحظة التسجيل فيبقى مفهومًا بعد الحذف', max_length=200, verbose_name='وصف السجل')),
                ('action', models.CharField(choices=[('create', 'إنشاء'), ('update', 'تعديل'), ('delete', 'حذف'), ('approve', 'اعتماد'), ('reject', 'رفض'), ('submit', 'رفع'), ('cancel', 'إلغاء'), ('export', 'تصدير'), ('login', 'دخول')], db_index=True, max_length=20, verbose_name='العملية')),
                ('changes', models.JSONField(blank=True, default=dict, help_text='{"field": {"from": "قديم", "to": "جديد"}}', verbose_name='التغييرات')),
                ('summary_ar', models.CharField(blank=True, max_length=300, verbose_name='الملخص')),
                ('actor_name', models.CharField(blank=True, help_text='يُحفظ نصًا فيبقى بعد حذف الشخص', max_length=200, verbose_name='اسم الفاعل')),
                ('actor_user_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='معرّف المستخدم')),
                ('channel', models.CharField(choices=[('web', 'المتصفح'), ('mobile', 'الجوال'), ('whatsapp', 'واتساب'), ('api', 'واجهة برمجية'), ('system', 'النظام')], default='web', max_length=20, verbose_name='القناة')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='العنوان')),
                ('note', models.TextField(blank=True, verbose_name='ملاحظة')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.account', verbose_name='الحساب')),
                ('actor_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to='employees.person', verbose_name='الفاعل')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_entries', to='accounts.company', verbose_name='الشركة')),
            ],
            options={
                'verbose_name': 'قيد تدقيق',
                'verbose_name_plural': 'سجل العمليات',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['account', 'object_type', 'object_id'], name='core_audite_account_6b2db4_idx'), models.Index(fields=['company', '-created_at'], name='core_audite_company_ac5a78_idx'), models.Index(fields=['actor_person', '-created_at'], name='core_audite_actor_p_e02aca_idx')],
            },
        ),
    ]
