# Generated by Django 5.2.6 on 2026-08-30 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_audit_rls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditentry',
            name='action',
            field=models.CharField(choices=[('create', 'إنشاء'), ('update', 'تعديل'), ('delete', 'حذف'), ('approve', 'اعتماد'), ('reject', 'رفض'), ('approved', 'اعتماد'), ('rejected', 'رفض'), ('submit', 'رفع'), ('cancel', 'إلغاء'), ('export', 'تصدير'), ('login', 'دخول')], db_index=True, max_length=20, verbose_name='العملية'),
        ),
    ]
