# Generated by Django 5.2.6 on 2026-09-01 10:25

import apps.core.models_files
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auth_tokens'),
        ('core', '0004_audit_decision_choices'),
        ('employees', '0004_assets_rls'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoredFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('kind', models.CharField(choices=[('avatar', 'صورة شخصية'), ('logo', 'شعار الشركة'), ('document', 'وثيقة موظف'), ('contract', 'عقد'), ('attachment', 'مرفق طلب'), ('other', 'أخرى')], db_index=True, max_length=20, verbose_name='النوع')),
                ('file', models.FileField(max_length=400, upload_to=apps.core.models_files._upload_to, verbose_name='الملف')),
                ('original_name', models.CharField(max_length=255, verbose_name='الاسم الأصلي')),
                ('content_type', models.CharField(blank=True, max_length=100, verbose_name='نوع المحتوى')),
                ('size_bytes', models.BigIntegerField(default=0, verbose_name='الحجم')),
                ('checksum', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='البصمة')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='محذوف')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='ملاحظة')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.account', verbose_name='الحساب')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stored_files', to='accounts.company', verbose_name='الشركة')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='employees.person', verbose_name='الشخص')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to='employees.person', verbose_name='رفعه')),
            ],
            options={
                'verbose_name': 'ملف',
                'verbose_name_plural': 'الملفات',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['account', 'kind', 'is_deleted'], name='core_stored_account_02929a_idx'), models.Index(fields=['person', 'kind'], name='core_stored_person__a16e94_idx'), models.Index(fields=['account', 'checksum'], name='core_stored_account_cc8bc1_idx')],
            },
        ),
    ]
