# Generated by Django 5.2.6 on 2026-09-10 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0051_feature_platform_write'),
        ('core', '0008_dashboard_pref_rls'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('name_ar', models.CharField(max_length=150, verbose_name='اسم التقرير')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='الوصف')),
                ('source', models.CharField(choices=[('employees', 'الموظفون'), ('attendance', 'الحضور'), ('leaves', 'الإجازات'), ('payroll', 'الرواتب')], max_length=20, verbose_name='المصدر')),
                ('fields', models.JSONField(default=list, verbose_name='الحقول')),
                ('filters', models.JSONField(blank=True, default=dict, verbose_name='التصفية')),
                ('sort_by', models.CharField(blank=True, max_length=60, verbose_name='الترتيب')),
                ('is_shared', models.BooleanField(default=False, help_text='مطفأ = يراه بانيه وحده', verbose_name='مشترك')),
                ('created_by_person_id', models.BigIntegerField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.account', verbose_name='الحساب')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.company', verbose_name='الشركة')),
            ],
            options={
                'verbose_name': 'تقرير مخصّص',
                'verbose_name_plural': 'التقارير المخصّصة',
                'ordering': ['name_ar'],
                'indexes': [models.Index(fields=['company', 'source'], name='idx_custrep_company_src')],
            },
        ),
    ]
