# Generated by Django 5.2.6 on 2026-09-10 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_custom_reports_rls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customreport',
            name='source',
            field=models.CharField(choices=[('employees', 'الموظفون'), ('attendance', 'الحضور'), ('requests', 'الطلبات'), ('payroll', 'الرواتب')], max_length=20, verbose_name='المصدر'),
        ),
    ]
