# Generated by Django 5.2.6 on 2026-09-10 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_builtin_roles_are_system'),
        ('core', '0011_report_source_requests'),
        ('employees', '0018_reset_days_one_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('code', models.CharField(max_length=40, verbose_name='الرمز')),
                ('name_ar', models.CharField(max_length=150, verbose_name='اسم القالب')),
                ('name_en', models.CharField(blank=True, max_length=150, verbose_name='بالإنجليزية')),
                ('body_ar', models.TextField(verbose_name='نصّ الخطاب')),
                ('body_en', models.TextField(blank=True, verbose_name='النصّ بالإنجليزية')),
                ('heading_ar', models.CharField(blank=True, max_length=200, verbose_name='العنوان')),
                ('addressee_ar', models.CharField(blank=True, max_length=200, verbose_name='موجّه إلى')),
                ('includes_salary', models.BooleanField(default=False, help_text='الطالب يختار إظهاره — ولا يُظهر إلا بطلبه', verbose_name='يتضمّن الراتب')),
                ('valid_days', models.PositiveSmallIntegerField(default=30, verbose_name='مدّة الصلاحية (يومًا)')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.account', verbose_name='الحساب')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.company', verbose_name='الشركة')),
            ],
            options={
                'verbose_name': 'قالب خطاب',
                'verbose_name_plural': 'قوالب الخطابات',
                'ordering': ['sort_order', 'name_ar'],
            },
        ),
        migrations.CreateModel(
            name='IssuedLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('request_id', models.BigIntegerField(blank=True, null=True)),
                ('letter_no', models.CharField(max_length=40, unique=True, verbose_name='رقم الخطاب')),
                ('heading_ar', models.CharField(blank=True, max_length=200, verbose_name='العنوان')),
                ('addressee_ar', models.CharField(blank=True, max_length=200, verbose_name='موجّه إلى')),
                ('body_ar', models.TextField(verbose_name='النصّ المجمَّد')),
                ('issued_on', models.DateField(db_index=True, verbose_name='تاريخ الإصدار')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='صالح حتى')),
                ('issued_by_person_id', models.BigIntegerField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.account', verbose_name='الحساب')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.company', verbose_name='الشركة')),
                ('employment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='letters', to='employees.employment', verbose_name='الموظف')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued', to='core.lettertemplate', verbose_name='القالب')),
            ],
            options={
                'verbose_name': 'خطاب صادر',
                'verbose_name_plural': 'الخطابات الصادرة',
                'ordering': ['-issued_on', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='lettertemplate',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uq_lettertpl_company_code'),
        ),
        migrations.AddIndex(
            model_name='issuedletter',
            index=models.Index(fields=['employment', 'issued_on'], name='idx_letter_emp_date'),
        ),
    ]
