# Generated by Django 5.2.6 on 2026-09-11 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_builtin_roles_are_system'),
        ('core', '0013_letters_rls'),
        ('employees', '0018_reset_days_one_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('code', models.CharField(max_length=40, verbose_name='الرمز')),
                ('title_ar', models.CharField(max_length=200, verbose_name='العنوان')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='بالإنجليزية')),
                ('body_ar', models.TextField(verbose_name='النصّ')),
                ('version', models.PositiveSmallIntegerField(default=1, verbose_name='النسخة')),
                ('effective_from', models.DateField(verbose_name='سريان من')),
                ('audience', models.CharField(choices=[('all', 'جميع الموظفين'), ('department', 'إدارة بعينها'), ('branch', 'فرع بعينه')], default='all', max_length=20, verbose_name='الفئة')),
                ('department_id', models.BigIntegerField(blank=True, null=True)),
                ('branch_id', models.BigIntegerField(blank=True, null=True)),
                ('requires_ack', models.BooleanField(default=True, help_text='مطفأ = تُنشر للاطّلاع بلا توقيع', verbose_name='يلزمه إقرار')),
                ('is_published', models.BooleanField(default=False, verbose_name='منشورة')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('published_by_person_id', models.BigIntegerField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.account', verbose_name='الحساب')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.company', verbose_name='الشركة')),
            ],
            options={
                'verbose_name': 'سياسة',
                'verbose_name_plural': 'السياسات',
                'ordering': ['-effective_from', 'title_ar'],
            },
        ),
        migrations.CreateModel(
            name='PolicyAcknowledgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('version', models.PositiveSmallIntegerField(verbose_name='النسخة المقَرّ بها')),
                ('acknowledged_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الإقرار')),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.account', verbose_name='الحساب')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.company', verbose_name='الشركة')),
                ('employment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_acks', to='employees.employment', verbose_name='الموظف')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acks', to='core.policy', verbose_name='السياسة')),
            ],
            options={
                'verbose_name': 'إقرار سياسة',
                'verbose_name_plural': 'إقرارات السياسات',
                'ordering': ['-acknowledged_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='policy',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uq_policy_company_code'),
        ),
        migrations.AddConstraint(
            model_name='policyacknowledgement',
            constraint=models.UniqueConstraint(fields=('policy', 'employment', 'version'), name='uq_ack_policy_emp_version'),
        ),
    ]
