# Generated by Django 5.2.6 on 2026-09-11 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_builtin_roles_are_system'),
        ('core', '0015_policies_rls'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('ticket_no', models.CharField(max_length=30, unique=True, verbose_name='رقم التذكرة')),
                ('subject', models.CharField(max_length=200, verbose_name='العنوان')),
                ('body', models.TextField(verbose_name='الشرح')),
                ('screenshot_url', models.CharField(max_length=500, verbose_name='صورة الشاشة')),
                ('kind', models.CharField(choices=[('bug', 'علّة'), ('question', 'استفسار'), ('feature', 'طلب ميزة')], default='bug', max_length=15, verbose_name='التصنيف')),
                ('priority', models.CharField(choices=[('normal', 'عادية'), ('high', 'عالية'), ('urgent', 'عاجلة')], default='normal', max_length=10, verbose_name='الأولوية')),
                ('status', models.CharField(choices=[('open', 'مفتوحة'), ('answered', 'رُدّ عليها'), ('waiting', 'بانتظار العميل'), ('resolved', 'مغلقة')], db_index=True, default='open', max_length=15, verbose_name='الحالة')),
                ('opened_by_person_id', models.BigIntegerField(db_index=True)),
                ('opened_by_name', models.CharField(blank=True, max_length=150)),
                ('sla_hours', models.PositiveSmallIntegerField(default=24, help_text='من باقته يوم فتحها — فترقيتها بعدها لا تُغيّر تعهّدنا', verbose_name='مهلة الاستجابة')),
                ('sla_business_hours', models.BooleanField(default=False)),
                ('due_at', models.DateTimeField(blank=True, null=True, verbose_name='موعد الاستجابة')),
                ('first_response_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('plan_code_at_open', models.CharField(blank=True, max_length=40)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.account', verbose_name='الحساب')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.company', verbose_name='الشركة')),
            ],
            options={
                'verbose_name': 'تذكرة دعم',
                'verbose_name_plural': 'تذاكر الدعم',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('body', models.TextField(verbose_name='الرسالة')),
                ('attachment_url', models.CharField(blank=True, max_length=500, verbose_name='مرفق')),
                ('from_support', models.BooleanField(default=False)),
                ('author_person_id', models.BigIntegerField(blank=True, null=True)),
                ('author_name', models.CharField(blank=True, max_length=150)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.account', verbose_name='الحساب')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.company', verbose_name='الشركة')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.supportticket')),
            ],
            options={
                'verbose_name': 'رسالة تذكرة',
                'verbose_name_plural': 'رسائل التذاكر',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['company', 'status'], name='idx_ticket_company_status'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['opened_by_person_id', 'status'], name='idx_ticket_person_status'),
        ),
    ]
