# Generated by Django 5.2.6 on 2026-09-13 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_builtin_roles_are_system'),
        ('core', '0018_platform_reads_tickets'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('name', models.CharField(help_text='لأيّ تكاملٍ هذا المفتاح', max_length=120, verbose_name='الاسم')),
                ('prefix', models.CharField(db_index=True, max_length=12, verbose_name='البادئة')),
                ('key_hash', models.CharField(max_length=255)),
                ('scopes', models.JSONField(default=list, verbose_name='النطاقات')),
                ('rate_limit_per_hour', models.PositiveIntegerField(default=1000, verbose_name='سقف الطلبات بالساعة')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل')),
                ('expires_on', models.DateField(blank=True, null=True, verbose_name='ينتهي في')),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_ip', models.CharField(blank=True, max_length=45)),
                ('call_count', models.PositiveIntegerField(default=0)),
                ('created_by_person_id', models.BigIntegerField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_reason', models.CharField(blank=True, max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.account', verbose_name='الحساب')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.company', verbose_name='الشركة')),
            ],
            options={
                'verbose_name': 'مفتاح API',
                'verbose_name_plural': 'مفاتيح API',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ApiCallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('path', models.CharField(max_length=200)),
                ('method', models.CharField(max_length=10)),
                ('status_code', models.PositiveSmallIntegerField()),
                ('ip', models.CharField(blank=True, max_length=45)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.account', verbose_name='الحساب')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.company', verbose_name='الشركة')),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='core.apikey')),
            ],
            options={
                'verbose_name': 'نداء API',
                'verbose_name_plural': 'نداءات API',
                'ordering': ['-at'],
            },
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['company', 'is_active'], name='idx_apikey_company_active'),
        ),
        migrations.AddIndex(
            model_name='apicalllog',
            index=models.Index(fields=['api_key', 'at'], name='idx_apicall_key_at'),
        ),
    ]
