# Generated by Django 5.2.6 on 2026-09-15 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_api_keys_rls'),
    ]

    operations = [
        migrations.AddField(
            model_name='lettertemplate',
            name='footer_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='letter_footers', to='core.storedfile', verbose_name='صورة التذييل'),
        ),
        migrations.AddField(
            model_name='lettertemplate',
            name='header_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='letter_headers', to='core.storedfile', verbose_name='صورة الترويسة'),
        ),
    ]
