# Generated by Django 5.2.6 on 2026-08-30 15:10

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0010_billing_inherit_base'),
        ('employees', '0002_employees_rls'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('code', models.CharField(max_length=30, verbose_name='الرمز')),
                ('name_ar', models.CharField(max_length=120, verbose_name='الاسم')),
                ('name_en', models.CharField(blank=True, max_length=120, verbose_name='الاسم بالإنجليزية')),
                ('name_ur', models.CharField(blank=True, max_length=120, verbose_name='الاسم بالأوردو')),
                ('start_time', models.TimeField(verbose_name='بداية الدوام')),
                ('end_time', models.TimeField(verbose_name='نهاية الدوام')),
                ('crosses_midnight', models.BooleanField(default=False, help_text='ورديات ليلية تبدأ مساءً وتنتهي صباحًا', verbose_name='تمتد لليوم التالي')),
                ('break_minutes', models.PositiveSmallIntegerField(default=60, verbose_name='دقائق الاستراحة')),
                ('grace_in_minutes', models.PositiveSmallIntegerField(default=0, verbose_name='سماح التأخير')),
                ('grace_out_minutes', models.PositiveSmallIntegerField(default=0, verbose_name='سماح الانصراف المبكر')),
                ('working_days', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), default=list, help_text='0=الأحد … 6=السبت', size=None, verbose_name='أيام العمل')),
                ('is_flexible', models.BooleanField(default=False, help_text='يُحتسب بإجمالي الساعات لا بوقت الحضور', verbose_name='دوام مرن')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.account', verbose_name='الحساب')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.company', verbose_name='الشركة')),
            ],
            options={
                'verbose_name': 'وردية',
                'verbose_name_plural': 'الورديات',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('work_date', models.DateField(db_index=True, verbose_name='التاريخ')),
                ('first_in', models.DateTimeField(blank=True, null=True, verbose_name='أول حضور')),
                ('last_out', models.DateTimeField(blank=True, null=True, verbose_name='آخر انصراف')),
                ('worked_minutes', models.PositiveIntegerField(default=0, verbose_name='دقائق العمل')),
                ('late_minutes', models.PositiveIntegerField(default=0, verbose_name='دقائق التأخير')),
                ('early_out_minutes', models.PositiveIntegerField(default=0, verbose_name='دقائق الانصراف المبكر')),
                ('overtime_minutes', models.PositiveIntegerField(default=0, verbose_name='دقائق العمل الإضافي')),
                ('approved_overtime_minutes', models.PositiveIntegerField(default=0, help_text='لا يدخل المسير إلا بعد الاعتماد', verbose_name='الإضافي المعتمد')),
                ('status', models.CharField(choices=[('present', 'حاضر'), ('absent', 'غائب'), ('leave', 'إجازة'), ('holiday', 'عطلة'), ('weekend', 'راحة أسبوعية'), ('partial', 'حضور جزئي'), ('not_scheduled', 'خارج جدول العمل')], db_index=True, max_length=20, verbose_name='الحالة')),
                ('punch_count', models.PositiveSmallIntegerField(default=0, verbose_name='عدد البصمات')),
                ('is_manually_adjusted', models.BooleanField(default=False, verbose_name='عُدّل يدويًا')),
                ('adjustment_note', models.TextField(blank=True, verbose_name='سبب التعديل')),
                ('computed_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الاحتساب')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.account', verbose_name='الحساب')),
                ('adjusted_by_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjusted_attendance_days', to='employees.person')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.company', verbose_name='الشركة')),
                ('employment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_days', to='employees.employment', verbose_name='الموظف')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='attendance.shift')),
            ],
            options={
                'verbose_name': 'سجل حضور يومي',
                'verbose_name_plural': 'سجلات الحضور اليومية',
                'ordering': ['-work_date'],
            },
        ),
        migrations.CreateModel(
            name='ShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('effective_from', models.DateField(db_index=True, verbose_name='سريان من')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='سريان إلى')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.account', verbose_name='الحساب')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.company', verbose_name='الشركة')),
                ('employment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to='employees.employment', verbose_name='الموظف')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='attendance.shift', verbose_name='الوردية')),
            ],
            options={
                'verbose_name': 'إسناد وردية',
                'verbose_name_plural': 'إسنادات الورديات',
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceMonthlySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('period_year', models.PositiveSmallIntegerField(verbose_name='السنة')),
                ('period_month', models.PositiveSmallIntegerField(verbose_name='الشهر')),
                ('worked_days', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='أيام العمل')),
                ('unpaid_absent_days', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='أيام الغياب بلا أجر')),
                ('paid_leave_days', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='أيام الإجازة المدفوعة')),
                ('late_minutes', models.PositiveIntegerField(default=0, verbose_name='دقائق التأخير')),
                ('approved_overtime_minutes', models.PositiveIntegerField(default=0, verbose_name='الإضافي المعتمد')),
                ('is_final', models.BooleanField(default=False, help_text='يُقفل عند اعتماد المسير', verbose_name='نهائي')),
                ('computed_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الاحتساب')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.account', verbose_name='الحساب')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.company', verbose_name='الشركة')),
                ('employment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_summaries', to='employees.employment')),
            ],
            options={
                'verbose_name': 'ملخص حضور شهري',
                'verbose_name_plural': 'ملخصات الحضور الشهرية',
                'constraints': [models.UniqueConstraint(fields=('employment', 'period_year', 'period_month'), name='uq_attendance_summary')],
            },
        ),
        migrations.CreateModel(
            name='AttendancePunch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('punched_at', models.DateTimeField(db_index=True, verbose_name='وقت البصمة')),
                ('source', models.CharField(choices=[('device', 'جهاز بصمة'), ('mobile', 'تطبيق جوال'), ('web', 'المتصفح'), ('whatsapp', 'واتساب'), ('manual', 'إدخال يدوي')], max_length=20, verbose_name='المصدر')),
                ('device_id', models.CharField(blank=True, max_length=60, verbose_name='معرّف الجهاز')),
                ('external_ref', models.CharField(blank=True, help_text='مفتاح فريد يمنع تكرار البصمة عند إعادة الإرسال', max_length=120, verbose_name='المرجع الخارجي')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='خط العرض')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='خط الطول')),
                ('raw_payload', models.JSONField(blank=True, default=dict, verbose_name='البيانات الخام')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.account', verbose_name='الحساب')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.company', verbose_name='الشركة')),
                ('employment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='punches', to='employees.employment', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'بصمة',
                'verbose_name_plural': 'البصمات',
                'ordering': ['-punched_at'],
                'indexes': [models.Index(fields=['employment', 'punched_at'], name='attendance__employm_5697a0_idx'), models.Index(fields=['company', 'punched_at'], name='attendance__company_5b19ac_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('external_ref__gt', '')), fields=('company', 'external_ref'), name='uq_punch_external_ref')],
            },
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uq_shift_code_per_company'),
        ),
        migrations.AddIndex(
            model_name='attendanceday',
            index=models.Index(fields=['company', 'work_date', 'status'], name='attendance__company_59ccc6_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendanceday',
            constraint=models.UniqueConstraint(fields=('employment', 'work_date'), name='uq_attendance_day'),
        ),
        migrations.AddConstraint(
            model_name='shiftassignment',
            constraint=models.UniqueConstraint(fields=('employment', 'effective_from'), name='uq_shift_assignment_per_date'),
        ),
    ]
