# Generated by Django 5.2.6 on 2026-09-01 11:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_storage_limit'),
        ('attendance', '0002_attendance_rls'),
        ('employees', '0004_assets_rls'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('code', models.CharField(max_length=20, verbose_name='الرمز')),
                ('name_ar', models.CharField(max_length=150, verbose_name='الاسم')),
                ('name_en', models.CharField(blank=True, max_length=150, verbose_name='بالإنجليزية')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='خط العرض')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='خط الطول')),
                ('radius_meters', models.IntegerField(default=100, help_text='حجم الموقع نفسه', validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(5000)], verbose_name='نصف القطر (متر)')),
                ('tolerance_meters', models.IntegerField(default=100, help_text='يُضاف لنصف القطر — بين 50 و500 متر', validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(500)], verbose_name='هامش التسامح (متر)')),
                ('enforce_geofence', models.BooleanField(default=True, help_text='عند تعطيله تُقبل البصمة من أي مكان', verbose_name='التحقق من الموقع الجغرافي')),
                ('city', models.CharField(blank=True, max_length=80, verbose_name='المدينة')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='العنوان')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='ملاحظة')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.account', verbose_name='الحساب')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.company', verbose_name='الشركة')),
                ('site_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_sites', to='employees.employment', verbose_name='مدير الموقع')),
            ],
            options={
                'verbose_name': 'موقع عمل',
                'verbose_name_plural': 'مواقع العمل',
                'ordering': ['name_ar'],
            },
        ),
        migrations.CreateModel(
            name='SiteAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_primary', models.BooleanField(default=False, help_text='موقعه المعتاد — للتقارير والافتراضات', verbose_name='الموقع الأساسي')),
                ('effective_from', models.DateField(blank=True, null=True, verbose_name='ساري من')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='ساري حتى')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.account', verbose_name='الحساب')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.company', verbose_name='الشركة')),
                ('employment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_assignments', to='employees.employment', verbose_name='الموظف')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='attendance.worksite', verbose_name='الموقع')),
            ],
            options={
                'verbose_name': 'إسناد موقع',
                'verbose_name_plural': 'إسنادات المواقع',
            },
        ),
        migrations.CreateModel(
            name='PunchDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('device_code', models.CharField(max_length=60, verbose_name='رمز الجهاز')),
                ('name_ar', models.CharField(max_length=120, verbose_name='الاسم')),
                ('api_key_hash', models.CharField(blank=True, db_index=True, help_text='مجزَّأ — الجهاز يرسل به بصماته', max_length=64, verbose_name='مفتاح الجهاز')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر اتصال')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.account', verbose_name='الحساب')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.company', verbose_name='الشركة')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='attendance.worksite', verbose_name='الموقع')),
            ],
            options={
                'verbose_name': 'جهاز بصمة',
                'verbose_name_plural': 'أجهزة البصمة',
            },
        ),
        migrations.AddConstraint(
            model_name='worksite',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uniq_worksite_code'),
        ),
        migrations.AddConstraint(
            model_name='siteassignment',
            constraint=models.UniqueConstraint(fields=('employment', 'site'), name='uniq_site_assignment'),
        ),
        migrations.AddConstraint(
            model_name='punchdevice',
            constraint=models.UniqueConstraint(fields=('company', 'device_code'), name='uniq_punch_device'),
        ),
    ]
