# Generated by Django 5.2.6 on 2026-09-05 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_worksites_rls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punchdevice',
            name='api_key_hash',
            field=models.CharField(blank=True, db_index=True, help_text='مجزَّأ — الجهاز يرسل به بصماته. والتجزئة تتجاوز 64 حرفًا، فالطول يتّسع لها', max_length=128, verbose_name='مفتاح الجهاز'),
        ),
    ]
