# Generated by Django 5.2.6 on 2026-09-05 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_alter_punchdevice_api_key_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punchdevice',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='attendance.worksite', verbose_name='الموقع'),
        ),
    ]
