# Generated by Django 5.2.6 on 2026-09-07 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_device_auth_fn'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shift',
            options={'ordering': ['start_time'], 'verbose_name': 'فترة عمل', 'verbose_name_plural': 'فترات العمل'},
        ),
        migrations.AlterModelOptions(
            name='shiftassignment',
            options={'ordering': ['-effective_from'], 'verbose_name': 'إسناد فترة عمل', 'verbose_name_plural': 'إسنادات فترات العمل'},
        ),
        migrations.AlterField(
            model_name='shift',
            name='crosses_midnight',
            field=models.BooleanField(default=False, help_text='فترات عمل ليلية تبدأ مساءً وتنتهي صباحًا', verbose_name='تمتد لليوم التالي'),
        ),
        migrations.AlterField(
            model_name='shiftassignment',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='attendance.shift', verbose_name='فترة العمل'),
        ),
    ]
