# Generated by Django 5.2.6 on 2026-09-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_alter_shift_options_alter_shiftassignment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='allow_mobile_punch',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='بصمة الجوال'),
        ),
    ]
