# Generated by Django 5.2.6 on 2026-09-08 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_invite_preview_trim'),
        ('attendance', '0009_shift_allow_mobile_punch'),
        ('employees', '0013_alter_employment_allow_mobile_punch'),
        ('leaves', '0013_exemption_and_default_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='is_default',
            field=models.BooleanField(default=False, help_text='يتبعها من لم تُسند له فترة — واحدة للشركة', verbose_name='الفترة الافتراضية'),
        ),
        migrations.AlterField(
            model_name='attendanceday',
            name='status',
            field=models.CharField(choices=[('present', 'حاضر'), ('absent', 'غائب'), ('leave', 'إجازة'), ('holiday', 'عطلة'), ('weekend', 'راحة أسبوعية'), ('partial', 'حضور جزئي'), ('not_scheduled', 'خارج جدول العمل'), ('exempt', 'معفيّ من البصمة')], db_index=True, max_length=20, verbose_name='الحالة'),
        ),
        migrations.CreateModel(
            name='AttendanceExemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('start_date', models.DateField(db_index=True, verbose_name='من')),
                ('end_date', models.DateField(blank=True, help_text='فارغ = غير محدّدة المدّة', null=True, verbose_name='إلى')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='السبب')),
                ('granted_by_person_id', models.BigIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='ساري')),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.account', verbose_name='الحساب')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.company', verbose_name='الشركة')),
                ('employment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_exemptions', to='employees.employment', verbose_name='الموظف')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exemptions', to='leaves.request', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'إعفاء من البصمة',
                'verbose_name_plural': 'الإعفاءات من البصمة',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['employment', 'is_active'], name='idx_exempt_emp_active')],
            },
        ),
    ]
