# Generated by Django 5.2.6 on 2026-09-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_exemption_rls'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceday',
            name='overtime_rate_choice',
            field=models.CharField(blank=True, help_text='x1_5 أو x2 — فارغ = الأساس الافتراضي', max_length=10, verbose_name='معامِل الإضافي'),
        ),
    ]
