# Generated by Django 5.2.6 on 2026-09-13 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_builtin_roles_are_system'),
        ('attendance', '0012_overtime_rate_choice'),
        ('employees', '0025_activities_rls'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresenceDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('work_date', models.DateField(db_index=True)),
                ('inside_minutes', models.PositiveIntegerField(default=0, verbose_name='داخل')),
                ('outside_minutes', models.PositiveIntegerField(default=0, verbose_name='خارج')),
                ('no_signal_minutes', models.PositiveIntegerField(default=0, verbose_name='بلا إشارة')),
                ('deductible_minutes', models.PositiveIntegerField(default=0, verbose_name='القابل للخصم')),
                ('suggested_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='الخصم المقترَح')),
                ('is_reviewed', models.BooleanField(db_index=True, default=False, verbose_name='رُوجع')),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='المعتمَد')),
                ('reviewed_by_person_id', models.BigIntegerField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.CharField(blank=True, max_length=255)),
                ('is_applied', models.BooleanField(db_index=True, default=False, verbose_name='دخل المسير')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.account', verbose_name='الحساب')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.company', verbose_name='الشركة')),
                ('employment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presence_days', to='employees.employment')),
            ],
            options={
                'verbose_name': 'تواجد يوم',
                'verbose_name_plural': 'التواجد اليوميّ',
                'ordering': ['-work_date'],
                'indexes': [models.Index(fields=['company', 'is_reviewed', 'is_applied'], name='idx_presday_review')],
                'constraints': [models.UniqueConstraint(fields=('employment', 'work_date'), name='uq_presenceday_emp_date')],
            },
        ),
        migrations.CreateModel(
            name='PresencePing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('work_date', models.DateField(db_index=True)),
                ('at', models.DateTimeField(db_index=True, verbose_name='الوقت')),
                ('state', models.CharField(choices=[('inside', 'داخل الموقع'), ('outside', 'خارج الموقع'), ('no_signal', 'لا إشارة')], max_length=12, verbose_name='الحالة')),
                ('distance_meters', models.IntegerField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.account', verbose_name='الحساب')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.company', verbose_name='الشركة')),
                ('employment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presence_pings', to='employees.employment')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presence_pings', to='attendance.worksite')),
            ],
            options={
                'verbose_name': 'نبضة تواجد',
                'verbose_name_plural': 'نبضات التواجد',
                'ordering': ['-at'],
                'indexes': [models.Index(fields=['employment', 'work_date'], name='idx_ping_emp_date'), models.Index(fields=['company', 'work_date'], name='idx_ping_company_date')],
            },
        ),
    ]
