# Generated by Django 5.2.6 on 2026-08-30 12:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0010_billing_inherit_base'),
    ]

    operations = [
        migrations.CreateModel(
            name='GosiScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name_ar', models.CharField(max_length=150)),
                ('description_ar', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'نظام تأميني',
                'verbose_name_plural': 'الأنظمة التأمينية',
            },
        ),
        migrations.CreateModel(
            name='GosiRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField(db_index=True, verbose_name='سريان من')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='سريان إلى')),
                ('employee_pension_rate', models.DecimalField(decimal_places=4, default=0, max_digits=6, verbose_name='معاشات — الموظف')),
                ('employer_pension_rate', models.DecimalField(decimal_places=4, default=0, max_digits=6, verbose_name='معاشات — صاحب العمل')),
                ('employee_saned_rate', models.DecimalField(decimal_places=4, default=0, max_digits=6, verbose_name='ساند — الموظف')),
                ('employer_saned_rate', models.DecimalField(decimal_places=4, default=0, max_digits=6, verbose_name='ساند — صاحب العمل')),
                ('employer_hazards_rate', models.DecimalField(decimal_places=4, default=0, max_digits=6, verbose_name='الأخطار المهنية — صاحب العمل')),
                ('min_subject_wage', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='الحد الأدنى للأجر الخاضع')),
                ('max_subject_wage', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='الحد الأعلى للأجر الخاضع')),
                ('source_note', models.CharField(blank=True, help_text='مصدر النسبة — للتدقيق', max_length=255, verbose_name='مرجع')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rates', to='payroll.gosischeme')),
            ],
            options={
                'verbose_name': 'نسبة تأمينات',
                'verbose_name_plural': 'نسب التأمينات',
                'ordering': ['scheme', '-effective_from'],
                'constraints': [models.UniqueConstraint(fields=('scheme', 'effective_from'), name='uq_gosi_rate_per_date')],
            },
        ),
        migrations.CreateModel(
            name='PayComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('code', models.CharField(max_length=40, verbose_name='الرمز')),
                ('name_ar', models.CharField(max_length=150, verbose_name='الاسم')),
                ('name_en', models.CharField(blank=True, max_length=150, verbose_name='الاسم بالإنجليزية')),
                ('name_ur', models.CharField(blank=True, max_length=150, verbose_name='الاسم بالأوردو')),
                ('component_type', models.CharField(choices=[('earning', 'استحقاق'), ('deduction', 'استقطاع')], max_length=20, verbose_name='النوع')),
                ('calculation_type', models.CharField(choices=[('fixed', 'مبلغ ثابت'), ('percent_of', 'نسبة من مكوّن آخر'), ('formula', 'معادلة')], default='fixed', max_length=20, verbose_name='طريقة الاحتساب')),
                ('percent_of_code', models.CharField(blank=True, help_text='رمز المكوّن الأساس عند النسبة — غالبًا BASIC', max_length=40, verbose_name='نسبة من')),
                ('percent_value', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='النسبة')),
                ('is_gosi_subject', models.BooleanField(default=False, help_text='يدخل في الأجر الخاضع لاشتراك التأمينات', verbose_name='خاضع للتأمينات')),
                ('is_eosb_subject', models.BooleanField(default=False, help_text='حسب العقد — الشركة تحدد ما يدخل', verbose_name='يدخل في نهاية الخدمة')),
                ('is_overtime_base', models.BooleanField(default=False, verbose_name='يدخل أساس الإضافي')),
                ('is_wps_subject', models.BooleanField(default=True, verbose_name='يظهر في حماية الأجور')),
                ('is_taxable', models.BooleanField(default=False, verbose_name='خاضع للضريبة')),
                ('display_order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='نشط')),
                ('is_system', models.BooleanField(default=False, help_text='لا يُحذف — مثل الراتب الأساسي', verbose_name='مكوّن نظامي')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.account', verbose_name='الحساب')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.company', verbose_name='الشركة')),
            ],
            options={
                'verbose_name': 'مكوّن أجر',
                'verbose_name_plural': 'مكوّنات الأجر',
                'ordering': ['display_order', 'code'],
                'constraints': [models.UniqueConstraint(fields=('company', 'code'), name='uq_paycomponent_code_per_company')],
            },
        ),
        migrations.CreateModel(
            name='PayrollSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('payroll_days_per_month', models.PositiveSmallIntegerField(default=30, help_text='القاعدة المعتمدة في السوق السعودي: 30 يومًا', validators=[django.core.validators.MinValueValidator(28), django.core.validators.MaxValueValidator(31)], verbose_name='أيام الشهر للاحتساب')),
                ('working_hours_per_day', models.DecimalField(decimal_places=2, default=8, max_digits=4, verbose_name='ساعات العمل اليومية')),
                ('ramadan_hours_per_day', models.DecimalField(decimal_places=2, default=6, max_digits=4, verbose_name='ساعات رمضان للمسلمين')),
                ('overtime_basis', models.CharField(choices=[('full_plus_half_basic', 'أجر ساعة الأجر الكامل + 50% من ساعة الأساسي'), ('basic_x1_5', 'أجر ساعة الأساسي × 1.5'), ('full_x1_5', 'أجر ساعة الأجر الكامل × 1.5')], default='full_plus_half_basic', max_length=30, verbose_name='أساس العمل الإضافي')),
                ('eosb_note', models.TextField(blank=True, help_text='ما يدخل في أجر المكافأة يحدده علم is_eosb_subject على كل مكوّن، حسب العقد', verbose_name='ملاحظة نهاية الخدمة')),
                ('negative_net_policy', models.CharField(choices=[('block', 'رفض المسير'), ('carry', 'ترحيل الفرق للشهر التالي')], default='block', max_length=20, verbose_name='سياسة الصافي السالب')),
                ('variance_threshold_percent', models.DecimalField(decimal_places=2, default=10, help_text='تغيّر الصافي بأكثر من هذه النسبة يظهر في شاشة المراجعة', max_digits=5, verbose_name='عتبة الفروقات %')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.account', verbose_name='الحساب')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.company', verbose_name='الشركة')),
            ],
            options={
                'verbose_name': 'إعدادات رواتب',
                'verbose_name_plural': 'إعدادات الرواتب',
                'constraints': [models.UniqueConstraint(fields=('company',), name='uq_payroll_settings_per_company')],
            },
        ),
    ]
