# Generated by Django 5.2.6 on 2026-08-30 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_payroll_rls'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollsettings',
            name='eosb_wage_basis',
            field=models.CharField(choices=[('not_set', 'لم يُحدَّد بعد'), ('basic_only', 'الأساسي وحده'), ('flagged', 'حسب أعلام المكوّنات (is_eosb_subject)')], default='not_set', help_text='يجب تحديده قبل أول مسير مستحقات', max_length=20, verbose_name='أساس أجر المكافأة'),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='exclude_unpaid_leave_from_service',
            field=models.BooleanField(default=False, help_text='خيار الشركة — لا افتراض مفروض (ق-24)', verbose_name='استبعاد الإجازات بلا أجر من مدة الخدمة'),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='merge_supplementary_into_regular',
            field=models.BooleanField(default=True, help_text='الافتراض: مسير واحد. الفصل خيار الشركة', verbose_name='دمج مسير الإضافي مع العام'),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='terminated_pay_in_regular_run',
            field=models.BooleanField(default=True, help_text='إن أُطفئ، يُدمج راتب الأيام في مسير المستحقات', verbose_name='راتب أيام المنتهية خدمته في المسير العام'),
        ),
    ]
