# Generated by Django 5.2.6 on 2026-08-30 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_run_types_and_eosb_basis'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollsettings',
            name='company_bears_employee_gosi',
            field=models.BooleanField(default=False, help_text='الافتراض: الخصم من الموظف. عند التفعيل يستلم راتبه كاملًا وتظهر الحصة في القسيمة مقابل بند «تحملته الشركة». يمكن استثناء موظف بعينه.', verbose_name='الشركة تتحمل حصة الموظف من التأمينات'),
        ),
    ]
