# Generated by Django 5.2.6 on 2026-08-30 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_billing_inherit_base'),
        ('employees', '0002_employees_rls'),
        ('payroll', '0004_company_bears_gosi'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('run_no', models.CharField(max_length=30, verbose_name='رقم المسير')),
                ('run_type', models.CharField(choices=[('regular', 'المسير العام'), ('supplementary', 'مسير الإضافي والإضافات'), ('settlement', 'مسير المستحقات ونهاية الخدمة')], db_index=True, default='regular', max_length=20, verbose_name='النوع')),
                ('period_year', models.PositiveSmallIntegerField(verbose_name='السنة')),
                ('period_month', models.PositiveSmallIntegerField(verbose_name='الشهر')),
                ('accrual_date', models.DateField(help_text='تُقرأ به نسب التأمينات وهياكل الرواتب — لا تاريخ اليوم', verbose_name='تاريخ الاستحقاق')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الصرف')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('calculating', 'قيد الاحتساب'), ('calculated', 'محتسب — بانتظار المراجعة'), ('submitted', 'مرفوع للاعتماد'), ('approved', 'معتمد'), ('paid', 'مصروف'), ('cancelled', 'ملغى'), ('failed', 'فشل الاحتساب')], db_index=True, default='draft', max_length=20, verbose_name='الحالة')),
                ('employee_count', models.PositiveIntegerField(default=0, verbose_name='عدد الموظفين')),
                ('total_gross', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='إجمالي الاستحقاقات')),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='إجمالي الاستقطاعات')),
                ('total_net', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='إجمالي الصافي')),
                ('total_employer_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='تكلفة صاحب العمل')),
                ('calculated_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الاحتساب')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الرفع')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الاعتماد')),
                ('variance_count', models.PositiveIntegerField(default=0, help_text='موظفون تغيّر صافيهم عن الشهر السابق فوق العتبة', verbose_name='عدد الفروقات')),
                ('error_log', models.JSONField(blank=True, default=list, verbose_name='سجل الأخطاء')),
                ('note', models.TextField(blank=True, verbose_name='ملاحظة')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.account', verbose_name='الحساب')),
                ('approved_by_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payroll_runs', to='employees.person', verbose_name='المعتمِد')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.company', verbose_name='الشركة')),
            ],
            options={
                'verbose_name': 'مسير رواتب',
                'verbose_name_plural': 'مسيرات الرواتب',
                'ordering': ['-period_year', '-period_month', 'run_type'],
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الأساسي')),
                ('gross_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='إجمالي الاستحقاقات')),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='إجمالي الاستقطاعات')),
                ('net_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='صافي المستحق')),
                ('employer_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='تكلفة صاحب العمل')),
                ('gosi_subject_wage', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الأجر الخاضع')),
                ('gosi_employee_share', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='حصة الموظف')),
                ('gosi_employer_share', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='حصة صاحب العمل')),
                ('gosi_borne_by_company', models.BooleanField(default=False, verbose_name='الشركة تحملت حصة الموظف')),
                ('worked_days', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='أيام العمل')),
                ('unpaid_absence_days', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='أيام الغياب')),
                ('unpaid_leave_days', models.DecimalField(decimal_places=2, default=0, help_text='منفصلة عن الغياب — حق مأذون لا مخالفة (ق-32)', max_digits=6, verbose_name='أيام الإجازة بلا أجر')),
                ('overtime_minutes', models.PositiveIntegerField(default=0, verbose_name='دقائق الإضافي')),
                ('payment_method', models.CharField(default='bank', max_length=20, verbose_name='طريقة الصرف')),
                ('iban', models.CharField(blank=True, max_length=24, verbose_name='الآيبان')),
                ('include_in_wps', models.BooleanField(default=False, verbose_name='في حماية الأجور')),
                ('previous_net', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='صافي الشهر السابق')),
                ('variance_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='نسبة الفرق')),
                ('has_variance', models.BooleanField(default=False, verbose_name='فرق يحتاج مراجعة')),
                ('calculation_trace', models.JSONField(blank=True, default=dict, verbose_name='خطوات الاحتساب')),
                ('warnings', models.JSONField(blank=True, default=list, verbose_name='تنبيهات')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.account', verbose_name='الحساب')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.company', verbose_name='الشركة')),
                ('employment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='employees.employment', verbose_name='الموظف')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='payroll.payrollrun')),
            ],
            options={
                'verbose_name': 'قسيمة راتب',
                'verbose_name_plural': 'قسائم الرواتب',
                'ordering': ['run', 'employment__employee_no'],
            },
        ),
        migrations.CreateModel(
            name='PayslipLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_code', models.CharField(max_length=40, verbose_name='الرمز')),
                ('name_ar', models.CharField(max_length=150, verbose_name='البيان')),
                ('line_type', models.CharField(choices=[('earning', 'استحقاق'), ('deduction', 'استقطاع'), ('employer_cost', 'تكلفة صاحب عمل'), ('info', 'بيان فقط')], max_length=20, verbose_name='النوع')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ')),
                ('explanation', models.CharField(blank=True, help_text='مثال: 3 أيام × 400 ريال', max_length=300, verbose_name='شرح الاحتساب')),
                ('display_order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('payslip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='payroll.payslip')),
            ],
            options={
                'verbose_name': 'بند قسيمة',
                'verbose_name_plural': 'بنود القسائم',
                'ordering': ['payslip', 'display_order', 'component_code'],
            },
        ),
        migrations.AddConstraint(
            model_name='payrollrun',
            constraint=models.UniqueConstraint(fields=('company', 'run_no'), name='uq_payroll_run_no'),
        ),
        migrations.AddConstraint(
            model_name='payrollrun',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['draft', 'calculating', 'calculated', 'submitted', 'approved', 'paid'])), fields=('company', 'run_type', 'period_year', 'period_month'), name='uq_active_run_per_period'),
        ),
        migrations.AddIndex(
            model_name='payslip',
            index=models.Index(fields=['company', 'run'], name='payroll_pay_company_337b30_idx'),
        ),
        migrations.AddIndex(
            model_name='payslip',
            index=models.Index(fields=['employment', '-created_at'], name='payroll_pay_employm_a388e3_idx'),
        ),
        migrations.AddConstraint(
            model_name='payslip',
            constraint=models.UniqueConstraint(fields=('run', 'employment'), name='uq_payslip_per_run'),
        ),
    ]
