# Generated by Django 5.2.6 on 2026-08-30 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_payroll_run_rls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payrollsettings',
            name='negative_net_policy',
        ),
        migrations.AddField(
            model_name='paycomponent',
            name='is_absence_base',
            field=models.BooleanField(default=True, help_text='ق-36: الافتراض أن الخصم على الإجمالي. الشركة تستثني بدلًا أو أكثر بإطفاء هذا العلم', verbose_name='يدخل أساس خصم الغياب'),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='exclude_zero_net_from_wps',
            field=models.BooleanField(default=True, help_text='الموظف بصافٍ صفري يُحذف من ملف البنك قبل الإرسال', verbose_name='استبعاد الصافي الصفري من ملف حماية الأجور'),
        ),
    ]
