# Generated by Django 5.2.6 on 2026-08-30 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_billing_inherit_base'),
        ('payroll', '0007_absence_base_and_net_floor'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('code', models.CharField(max_length=30, verbose_name='الرمز')),
                ('name_ar', models.CharField(max_length=120, verbose_name='اسم القالب')),
                ('bank_name_ar', models.CharField(max_length=120, verbose_name='البنك')),
                ('swift_prefix', models.CharField(blank=True, help_text='NCBK للأهلي، RJHI للراجحي', max_length=4, verbose_name='رمز سويفت')),
                ('file_format', models.CharField(choices=[('csv', 'CSV'), ('txt', 'نصي بفاصل'), ('xlsx', 'إكسل')], default='csv', max_length=10, verbose_name='الصيغة')),
                ('delimiter', models.CharField(default=',', max_length=3, verbose_name='الفاصل')),
                ('include_header', models.BooleanField(default=True, verbose_name='يتضمن سطر ترويسة')),
                ('line_ending', models.CharField(choices=[('crlf', 'ويندوز CRLF'), ('lf', 'يونكس LF')], default='crlf', max_length=10, verbose_name='نهاية السطر')),
                ('encoding', models.CharField(default='utf-8', max_length=20, verbose_name='الترميز')),
                ('filename_pattern', models.CharField(default='{bank}_For_{date}.csv', help_text='متغيرات: {bank} {date} {period} {company}', max_length=120, verbose_name='نمط اسم الملف')),
                ('is_builtin', models.BooleanField(default=False, help_text='مبني على مواصفات موثّقة من البنك', verbose_name='قالب جاهز')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('note', models.TextField(blank=True, verbose_name='ملاحظة')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.account', verbose_name='الحساب')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.company', verbose_name='الشركة')),
            ],
            options={
                'verbose_name': 'قالب بنك',
                'verbose_name_plural': 'قوالب البنوك',
                'ordering': ['bank_name_ar'],
            },
        ),
        migrations.CreateModel(
            name='BankColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(verbose_name='الترتيب')),
                ('header', models.CharField(max_length=80, verbose_name='عنوان العمود')),
                ('source', models.CharField(choices=[('employee_bank_swift', 'رمز بنك الموظف'), ('iban', 'الآيبان'), ('account_number', 'رقم الحساب'), ('net_pay', 'صافي المستحق'), ('gross', 'إجمالي الاستحقاقات'), ('basic', 'الراتب الأساسي'), ('housing', 'بدل السكن'), ('other_earnings', 'باقي الاستحقاقات'), ('deductions', 'إجمالي الاستقطاعات'), ('employee_no', 'الرقم الوظيفي'), ('name_ar', 'الاسم بالعربية'), ('name_en', 'الاسم بالإنجليزية'), ('id_number', 'رقم الهوية'), ('department', 'القسم'), ('branch', 'الفرع'), ('job_title', 'المسمى الوظيفي'), ('constant', 'قيمة ثابتة'), ('sequence', 'رقم تسلسلي')], max_length=40, verbose_name='المصدر')),
                ('constant_value', models.CharField(blank=True, help_text='عند المصدر: قيمة ثابتة', max_length=120, verbose_name='القيمة الثابتة')),
                ('number_format', models.CharField(blank=True, help_text='مثال: 0.00 لخانتين عشريتين', max_length=20, verbose_name='تنسيق الرقم')),
                ('text_transform', models.CharField(blank=True, choices=[('upper', 'حروف كبيرة'), ('lower', 'حروف صغيرة'), ('strip', 'إزالة المسافات')], max_length=20, verbose_name='تحويل النص')),
                ('max_length', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='أقصى طول')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='payroll.banktemplate')),
            ],
            options={
                'verbose_name': 'عمود قالب',
                'verbose_name_plural': 'أعمدة القوالب',
                'ordering': ['template', 'position'],
            },
        ),
        migrations.AddConstraint(
            model_name='banktemplate',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uq_bank_template_code'),
        ),
        migrations.AddConstraint(
            model_name='bankcolumn',
            constraint=models.UniqueConstraint(fields=('template', 'position'), name='uq_bank_column_position'),
        ),
    ]
