# Generated by Django 5.2.6 on 2026-08-30 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0009_bank_templates_rls'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollsettings',
            name='payslip_show_employer_gosi',
            field=models.BooleanField(default=False, help_text='تخصّ الشركة لا الموظف', verbose_name='عرض حصة صاحب العمل في القسيمة'),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='payslip_show_leave_balance',
            field=models.BooleanField(default=False, help_text='القسيمة للراتب — الرصيد في شاشة الإجازات', verbose_name='عرض رصيد الإجازات في القسيمة'),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='payslip_show_previous_month',
            field=models.BooleanField(default=False, help_text='قد يثير أسئلة أكثر مما يجيب', verbose_name='عرض مقارنة بالشهر السابق'),
        ),
    ]
