# Generated by Django 5.2.6 on 2026-08-30 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0010_payslip_display_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslipline',
            name='name_en',
            field=models.CharField(blank=True, max_length=150, verbose_name='البيان بالإنجليزية'),
        ),
        migrations.AddField(
            model_name='payslipline',
            name='name_ur',
            field=models.CharField(blank=True, max_length=150, verbose_name='البيان بالأوردو'),
        ),
    ]
