# Generated by Django 5.2.6 on 2026-08-30 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0011_payslip_line_locales'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollsettings',
            name='advance_block_if_outstanding',
            field=models.BooleanField(default=True, verbose_name='منع سلفة ثانية قبل سداد الأولى'),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='advance_max_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='فارغ = بلا حد. يُقارن بالمبلغ المطلوب', max_digits=12, null=True, verbose_name='الحد الأقصى للسلفة'),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='advance_max_installments',
            field=models.PositiveSmallIntegerField(default=12, verbose_name='أقصى عدد أقساط'),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='advance_max_months_of_salary',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='مثال: 3 تعني راتب ثلاثة أشهر', max_digits=4, null=True, verbose_name='الحد الأقصى بعدد الرواتب'),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='advances_enabled',
            field=models.BooleanField(default=True, help_text='عند الإطفاء تختفي السلف من الطلبات والقسيمة والتقارير', verbose_name='تمكين نظام السلف'),
        ),
    ]
