# Generated by Django 5.2.6 on 2026-08-31 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0012_assets_advances_documents'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('iban_code', models.CharField(db_index=True, max_length=2, unique=True, verbose_name='رمز الآيبان')),
                ('name_ar', models.CharField(max_length=120, verbose_name='الاسم')),
                ('name_en', models.CharField(blank=True, max_length=120, verbose_name='بالإنجليزية')),
                ('short_ar', models.CharField(blank=True, max_length=40, verbose_name='المختصر')),
                ('swift', models.CharField(blank=True, max_length=11, verbose_name='سويفت')),
                ('kind', models.CharField(choices=[('local', 'بنك محلي'), ('digital', 'بنك رقمي / محفظة'), ('foreign', 'فرع بنك أجنبي'), ('central', 'البنك المركزي')], default='local', max_length=12, verbose_name='النوع')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('supports_wps', models.BooleanField(default=True, verbose_name='يقبل ملفات حماية الأجور')),
                ('display_order', models.IntegerField(default=100, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'بنك',
                'verbose_name_plural': 'البنوك',
                'ordering': ['display_order', 'name_ar'],
            },
        ),
    ]
