# Generated by Django 5.2.6 on 2026-09-04 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_accountmembership_is_founding_owner_and_more'),
        ('employees', '0010_employment_termination_pending_from'),
        ('leaves', '0011_alter_delegation_request'),
        ('payroll', '0013_banks'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetroAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('period_year', models.PositiveSmallIntegerField(verbose_name='سنة الاستحقاق')),
                ('period_month', models.PositiveSmallIntegerField(verbose_name='شهر الاستحقاق')),
                ('source', models.CharField(choices=[('attendance_fix', 'تصحيح بصمة'), ('leave', 'إجازة بأثر رجعي'), ('overtime', 'عمل إضافي متأخر'), ('other', 'تعديل آخر')], max_length=20, verbose_name='المصدر')),
                ('amount_before', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='المحتسب سابقًا')),
                ('amount_after', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='المحتسب بالبيانات المصححة')),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='موجب: يُضاف للموظف · سالب: يُخصم منه', max_digits=12, verbose_name='الفرق')),
                ('reason_ar', models.CharField(blank=True, max_length=200, verbose_name='البيان')),
                ('status', models.CharField(choices=[('pending', 'بانتظار الإدراج'), ('merged', 'مُدرجة في مسير'), ('deferred', 'مؤجَّلة'), ('cancelled', 'ملغاة')], db_index=True, default='pending', max_length=20, verbose_name='الحالة')),
                ('decided_by_person_id', models.BigIntegerField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='ملاحظة')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.account', verbose_name='الحساب')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.company', verbose_name='الشركة')),
                ('employment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retro_adjustments', to='employees.employment', verbose_name='الموظف')),
                ('merged_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retro_adjustments', to='payroll.payrollrun', verbose_name='المسير المُدرجة فيه')),
                ('source_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retro_adjustments', to='leaves.request', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'تسوية رجعية',
                'verbose_name_plural': 'التسويات الرجعية',
                'ordering': ['-period_year', '-period_month', '-id'],
                'indexes': [models.Index(fields=['company', 'status'], name='payroll_ret_company_fdddc6_idx'), models.Index(fields=['employment', 'period_year', 'period_month'], name='payroll_ret_employm_99d934_idx')],
            },
        ),
    ]
