# Generated by Django 5.2.6 on 2026-09-04 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0015_retro_rls'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollsettings',
            name='retro_method',
            field=models.CharField(choices=[('next_run', 'تسوية في المسير التالي'), ('recalc', 'إعادة احتساب المسير القديم')], default='next_run', help_text='إعادة الاحتساب ممكنة خلال 48 ساعة من إغلاق المسير — وبعدها تصير التسوية في التالي حتمًا', max_length=20, verbose_name='طريقة التسوية الرجعية'),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='retro_reopen_hours',
            field=models.PositiveSmallIntegerField(default=48, help_text='بعدها لا يُمسّ المسير المغلق (ق-44)', verbose_name='مهلة إعادة فتح المسير (ساعات)'),
        ),
    ]
