# Generated by Django 5.2.6 on 2026-09-04 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0016_payrollsettings_retro_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retroadjustment',
            name='status',
            field=models.CharField(choices=[('pending', 'بانتظار القرار'), ('selected', 'مختارة للإدراج'), ('merged', 'مُدرجة في مسير'), ('deferred', 'مؤجَّلة'), ('cancelled', 'ملغاة')], db_index=True, default='pending', max_length=20, verbose_name='الحالة'),
        ),
    ]
