# Generated by Django 5.2.6 on 2026-09-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0017_alter_retroadjustment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollsettings',
            name='eosb_wage_basis',
            field=models.CharField(choices=[('not_set', 'لم يُحدَّد بعد'), ('basic_only', 'الراتب الأساسي فقط'), ('basic_housing', 'الراتب الأساسي + بدل السكن'), ('basic_housing_transport', 'الراتب الأساسي + بدل السكن والمواصلات'), ('basic_all', 'الراتب الأساسي + جميع البدلات'), ('flagged', 'حسب أعلام المكوّنات (قديم)')], default='not_set', help_text='يجب تحديده قبل أول مسير مستحقات', max_length=30, verbose_name='أساس أجر المكافأة'),
        ),
    ]
