# Generated by Django 5.2.6 on 2026-09-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0018_alter_payrollsettings_eosb_wage_basis'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollsettings',
            name='allow_mobile_punch',
            field=models.BooleanField(default=True, verbose_name='بصمة الجوال'),
        ),
    ]
