# Generated by Django 5.2.6 on 2026-09-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0019_payrollsettings_allow_mobile_punch'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollsettings',
            name='penalties_deduct_enabled',
            field=models.BooleanField(default=True, verbose_name='خصم الجزاءات من الرواتب'),
        ),
    ]
