# Generated by Django 5.2.6 on 2026-09-11 22:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_builtin_roles_are_system'),
        ('employees', '0022_tags_tasks_rls'),
        ('payroll', '0020_penalty_optional_deduction'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimableAllowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('code', models.CharField(max_length=40, verbose_name='الرمز')),
                ('name_ar', models.CharField(max_length=120, verbose_name='المخصّص')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='الوصف')),
                ('mode', models.CharField(choices=[('fixed', 'مبلغ ثابت'), ('cap', 'سقف أعلى')], default='fixed', max_length=10, verbose_name='نوع المبلغ')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='المبلغ أو السقف')),
                ('requires_attachment', models.BooleanField(default=False, help_text='كفاتورةٍ تُثبت الصرف', verbose_name='يلزمه مرفق')),
                ('component_code', models.CharField(blank=True, help_text='يُصرف به في القسيمة — فارغ = يدويًّا', max_length=40, verbose_name='بند المسير')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.account', verbose_name='الحساب')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.company', verbose_name='الشركة')),
            ],
            options={
                'verbose_name': 'مخصّص مصروف',
                'verbose_name_plural': 'المخصّصات المصروفة',
                'ordering': ['sort_order', 'name_ar'],
            },
        ),
        migrations.CreateModel(
            name='AllowanceEligibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('custom_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='مبلغ خاصّ')),
                ('granted_by_person_id', models.BigIntegerField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.account', verbose_name='الحساب')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.company', verbose_name='الشركة')),
                ('employment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowance_eligibilities', to='employees.employment', verbose_name='الموظف')),
                ('allowance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibilities', to='payroll.claimableallowance', verbose_name='المخصّص')),
            ],
            options={
                'verbose_name': 'استحقاق مخصّص',
                'verbose_name_plural': 'استحقاقات المخصّصات',
            },
        ),
        migrations.AddConstraint(
            model_name='claimableallowance',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uq_claimallow_company_code'),
        ),
        migrations.AddConstraint(
            model_name='allowanceeligibility',
            constraint=models.UniqueConstraint(fields=('allowance', 'employment'), name='uq_alloweligib_allow_emp'),
        ),
    ]
