# Generated by Django 5.2.6 on 2026-09-11 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_builtin_roles_are_system'),
        ('employees', '0022_tags_tasks_rls'),
        ('payroll', '0022_allowances_rls'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowanceClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('request_id', models.BigIntegerField(db_index=True, unique=True)),
                ('claim_date', models.DateField(db_index=True, verbose_name='تاريخ الاستحقاق')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ')),
                ('method', models.CharField(blank=True, choices=[('payroll', 'يُدرج في المسير'), ('outside', 'صُرف خارج المسير')], help_text='فارغ = لم يُقرَّر بعد', max_length=15, verbose_name='طريقة الصرف')),
                ('payroll_run_type', models.CharField(blank=True, max_length=20, verbose_name='نوع المسير')),
                ('payroll_run_id', models.BigIntegerField(blank=True, null=True)),
                ('paid_on', models.DateField(blank=True, null=True, verbose_name='تاريخ الصرف')),
                ('paid_by_person_id', models.BigIntegerField(blank=True, null=True)),
                ('paid_note', models.CharField(blank=True, max_length=255, verbose_name='ملاحظة الصرف')),
                ('is_settled', models.BooleanField(db_index=True, default=False, verbose_name='صُرف')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.account', verbose_name='الحساب')),
                ('allowance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='payroll.claimableallowance')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.company', verbose_name='الشركة')),
                ('employment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allowance_claims', to='employees.employment')),
            ],
            options={
                'verbose_name': 'مخصّص معتمد',
                'verbose_name_plural': 'المخصّصات المعتمدة',
                'ordering': ['-claim_date', '-id'],
                'indexes': [models.Index(fields=['company', 'is_settled'], name='idx_claim_company_settled')],
            },
        ),
    ]
