# Generated by Django 5.2.6 on 2026-09-12 12:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_builtin_roles_are_system'),
        ('employees', '0022_tags_tasks_rls'),
        ('payroll', '0024_claims_rls'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('kind', models.CharField(choices=[('earning', 'إضافة'), ('deduction', 'حسم')], max_length=12, verbose_name='النوع')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='المبلغ الشهري')),
                ('start_year', models.PositiveSmallIntegerField(verbose_name='من سنة')),
                ('start_month', models.PositiveSmallIntegerField(verbose_name='من شهر')),
                ('end_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('end_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_occurrences', models.PositiveSmallIntegerField(blank=True, help_text='كقسطٍ ينتهي — فارغ إن كانت النهاية بتاريخ', null=True, verbose_name='عدد المرّات')),
                ('applied_count', models.PositiveSmallIntegerField(default=0, verbose_name='طُبّق مرّات')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='السبب')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='سارٍ')),
                ('created_by_person_id', models.BigIntegerField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.account', verbose_name='الحساب')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.company', verbose_name='الشركة')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_adjustments', to='payroll.paycomponent', verbose_name='البند')),
                ('employment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_adjustments', to='employees.employment', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'بند مكرّر',
                'verbose_name_plural': 'البنود المكرّرة',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['company', 'is_active'], name='idx_recur_company_active'), models.Index(fields=['employment', 'is_active'], name='idx_recur_emp_active')],
            },
        ),
    ]
