# Generated by Django 5.2.6 on 2026-09-12 12:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_builtin_roles_are_system'),
        ('employees', '0022_tags_tasks_rls'),
        ('payroll', '0026_recurring_rls'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayslipDeferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('component_code', models.CharField(max_length=40, verbose_name='رمز البند')),
                ('name_ar', models.CharField(max_length=150, verbose_name='البيان')),
                ('line_type', models.CharField(max_length=20, verbose_name='نوع البند')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='المبلغ')),
                ('from_year', models.PositiveSmallIntegerField()),
                ('from_month', models.PositiveSmallIntegerField()),
                ('to_year', models.PositiveSmallIntegerField(verbose_name='إلى سنة')),
                ('to_month', models.PositiveSmallIntegerField(verbose_name='إلى شهر')),
                ('reason', models.CharField(max_length=255, verbose_name='السبب')),
                ('status', models.CharField(choices=[('pending', 'مؤجَّل'), ('applied', 'طُبّق'), ('cancelled', 'أُلغي')], db_index=True, default='pending', max_length=12, verbose_name='الحالة')),
                ('advance_id', models.BigIntegerField(blank=True, null=True)),
                ('applied_run_id', models.BigIntegerField(blank=True, null=True)),
                ('deferred_by_person_id', models.BigIntegerField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.account', verbose_name='الحساب')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.company', verbose_name='الشركة')),
                ('employment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deferrals', to='employees.employment')),
                ('payslip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deferrals', to='payroll.payslip', verbose_name='القسيمة')),
            ],
            options={
                'verbose_name': 'بند مؤجَّل',
                'verbose_name_plural': 'البنود المؤجَّلة',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['company', 'status'], name='idx_defer_company_status'), models.Index(fields=['to_year', 'to_month', 'status'], name='idx_defer_target')],
            },
        ),
    ]
