# Generated by Django 5.2.6 on 2026-09-12 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0028_deferral_rls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslipdeferral',
            name='payslip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deferrals', to='payroll.payslip', verbose_name='القسيمة'),
        ),
    ]
