# Generated by Django 5.2.6 on 2026-09-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0029_deferral_survives_recalc'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollsettings',
            name='overtime_basis_holiday',
            field=models.CharField(blank=True, choices=[('full_plus_half_basic', 'أجر ساعة الأجر الكامل + 50% من ساعة الأساسي'), ('basic_x1_5', 'أجر ساعة الأساسي × 1.5'), ('full_x1_5', 'أجر ساعة الأجر الكامل × 1.5'), ('full_plus_basic', 'أجر ساعة الأجر الكامل + ساعة الأساسي'), ('full_x2', 'أجر ساعة الأجر الكامل × 2')], help_text='فارغ = كاليوم العادي', max_length=30, verbose_name='أساس الإضافي في العيد والعطلة الرسمية'),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='overtime_basis_weekend',
            field=models.CharField(blank=True, choices=[('full_plus_half_basic', 'أجر ساعة الأجر الكامل + 50% من ساعة الأساسي'), ('basic_x1_5', 'أجر ساعة الأساسي × 1.5'), ('full_x1_5', 'أجر ساعة الأجر الكامل × 1.5'), ('full_plus_basic', 'أجر ساعة الأجر الكامل + ساعة الأساسي'), ('full_x2', 'أجر ساعة الأجر الكامل × 2')], help_text='فارغ = كاليوم العادي', max_length=30, verbose_name='أساس الإضافي في الراحة الأسبوعية'),
        ),
        migrations.AlterField(
            model_name='payrollsettings',
            name='overtime_basis',
            field=models.CharField(choices=[('full_plus_half_basic', 'أجر ساعة الأجر الكامل + 50% من ساعة الأساسي'), ('basic_x1_5', 'أجر ساعة الأساسي × 1.5'), ('full_x1_5', 'أجر ساعة الأجر الكامل × 1.5'), ('full_plus_basic', 'أجر ساعة الأجر الكامل + ساعة الأساسي'), ('full_x2', 'أجر ساعة الأجر الكامل × 2')], default='full_plus_half_basic', max_length=30, verbose_name='أساس العمل الإضافي'),
        ),
    ]
