# Generated by Django 5.2.6 on 2026-09-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0030_overtime_holiday_basis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payrollsettings',
            name='overtime_basis_holiday',
        ),
        migrations.RemoveField(
            model_name='payrollsettings',
            name='overtime_basis_weekend',
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='allow_overtime_rate_choice',
            field=models.BooleanField(default=False, help_text='يُظهر للموظف خيار ×2 في طلب الإضافي — للعطل والظروف التي تعتمدها الشركة', verbose_name='السماح باختيار معامِل الإضافي'),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='overtime_basis_x2',
            field=models.CharField(choices=[('full_plus_half_basic', 'أجر ساعة الأجر الكامل + 50% من ساعة الأساسي'), ('basic_x1_5', 'أجر ساعة الأساسي × 1.5'), ('full_x1_5', 'أجر ساعة الأجر الكامل × 1.5'), ('full_plus_basic', 'أجر ساعة الأجر الكامل + ساعة الأساسي'), ('full_x2', 'أجر ساعة الأجر الكامل × 2')], default='full_x2', help_text='يُستعمل حين يختار الموظف ×2 ويُعتمد طلبه', max_length=30, verbose_name='أساس معامِل ×2'),
        ),
    ]
