# Generated by Django 5.2.6 on 2026-09-12 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0031_overtime_rate_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollsettings',
            name='allow_leave_cashout',
            field=models.BooleanField(default=False, help_text='⚠️ الصرف بلا استخدامٍ فعليّ أو انتهاء علاقة مخالفٌ لنظام العمل — والمسؤولية على صاحب العمل', verbose_name='السماح بمخالصة الإجازة أثناء الخدمة'),
        ),
    ]
