# Generated by Django 5.2.6 on 2026-09-12 15:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_builtin_roles_are_system'),
        ('employees', '0022_tags_tasks_rls'),
        ('payroll', '0032_leave_cashout'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollsettings',
            name='expense_default_method',
            field=models.CharField(default='payroll', help_text='payroll = في المسير · outside = خارجه', max_length=15, verbose_name='آلية الصرف الافتراضية'),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='expense_max_age_days',
            field=models.PositiveSmallIntegerField(default=90, help_text='⚠️ فمطالبةٌ بعد سنة يتعذّر التحقّق منها', verbose_name='أقصى قِدَم للمطالبة (يومًا)'),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='expenses_enabled',
            field=models.BooleanField(default=False, verbose_name='تمكين المصروفات'),
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('code', models.CharField(max_length=40, verbose_name='الرمز')),
                ('name_ar', models.CharField(max_length=120, verbose_name='الفئة')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='الوصف')),
                ('max_per_claim', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='سقف المطالبة')),
                ('max_per_month', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='سقف الشهر')),
                ('component_code', models.CharField(blank=True, help_text='يُصرف به في القسيمة — فارغ = يدويًّا', max_length=40, verbose_name='بند المسير')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّلة')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.account', verbose_name='الحساب')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.company', verbose_name='الشركة')),
            ],
            options={
                'verbose_name': 'فئة مصروف',
                'verbose_name_plural': 'فئات المصروفات',
                'ordering': ['sort_order', 'name_ar'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('claim_no', models.CharField(max_length=30, unique=True, verbose_name='رقم المطالبة')),
                ('spent_on', models.DateField(db_index=True, verbose_name='تاريخ الصرف')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='المبلغ المدفوع')),
                ('description', models.CharField(max_length=255, verbose_name='البيان')),
                ('receipt_url', models.CharField(max_length=500, verbose_name='الفاتورة')),
                ('status', models.CharField(choices=[('pending', 'قيد الاعتماد'), ('approved', 'معتمدة'), ('rejected', 'مرفوضة'), ('settled', 'صُرفت')], db_index=True, default='pending', max_length=12, verbose_name='الحالة')),
                ('decided_by_person_id', models.BigIntegerField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.CharField(blank=True, max_length=255, verbose_name='سبب القرار')),
                ('method', models.CharField(blank=True, max_length=15, verbose_name='طريقة الصرف')),
                ('payroll_run_type', models.CharField(blank=True, max_length=20)),
                ('paid_on', models.DateField(blank=True, null=True)),
                ('paid_note', models.CharField(blank=True, max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.account', verbose_name='الحساب')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='payroll.expensecategory', verbose_name='الفئة')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.company', verbose_name='الشركة')),
                ('employment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_claims', to='employees.employment', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'مطالبة مصروف',
                'verbose_name_plural': 'مطالبات المصروفات',
                'ordering': ['-spent_on', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='expensecategory',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uq_expcat_company_code'),
        ),
        migrations.AddIndex(
            model_name='expenseclaim',
            index=models.Index(fields=['company', 'status'], name='idx_expclaim_company_status'),
        ),
        migrations.AddIndex(
            model_name='expenseclaim',
            index=models.Index(fields=['employment', 'spent_on'], name='idx_expclaim_emp_date'),
        ),
    ]
