# Generated by Django 5.2.6 on 2026-09-12 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_builtin_roles_are_system'),
        ('payroll', '0034_expenses_rls'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('step_order', models.PositiveSmallIntegerField(verbose_name='الترتيب')),
                ('title', models.CharField(blank=True, max_length=120)),
                ('decision', models.CharField(choices=[('pending', 'قيد الانتظار'), ('approved', 'معتمد'), ('rejected', 'مرفوض')], db_index=True, default='pending', max_length=12, verbose_name='القرار')),
                ('decided_by_person_id', models.BigIntegerField(blank=True, null=True)),
                ('decided_by_name', models.CharField(blank=True, max_length=150)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='السبب')),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.account', verbose_name='الحساب')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.company', verbose_name='الشركة')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_approvals', to='accounts.role')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='payroll.payrollrun', verbose_name='المسير')),
            ],
            options={
                'verbose_name': 'اعتماد مسير',
                'verbose_name_plural': 'اعتمادات المسير',
                'ordering': ['run', 'step_order'],
                'constraints': [models.UniqueConstraint(fields=('run', 'step_order'), name='uq_payrollapproval_run_step')],
            },
        ),
        migrations.CreateModel(
            name='PayrollApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('step_order', models.PositiveSmallIntegerField(verbose_name='الترتيب')),
                ('title', models.CharField(blank=True, max_length=120, verbose_name='مسمّى الخطوة')),
                ('sla_hours', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='مهلة الاعتماد (ساعة)')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّلة')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.account', verbose_name='الحساب')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.company', verbose_name='الشركة')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_steps', to='accounts.role', verbose_name='الدور المعتمِد')),
            ],
            options={
                'verbose_name': 'خطوة اعتماد مسير',
                'verbose_name_plural': 'خطوات اعتماد المسير',
                'ordering': ['step_order'],
                'constraints': [models.UniqueConstraint(fields=('company', 'step_order'), name='uq_payrollstep_company_order')],
            },
        ),
    ]
