# Generated by Django 5.2.6 on 2026-09-12 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0036_payroll_approval_rls'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollsettings',
            name='activities_enabled',
            field=models.BooleanField(default=False, verbose_name='تمكين أنشطة العمل'),
        ),
    ]
