# Generated by Django 5.2.6 on 2026-09-13 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0037_activities_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollsettings',
            name='presence_retention_days',
            field=models.PositiveSmallIntegerField(default=90, verbose_name='مدّة حفظ النبضات (يومًا)'),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='presence_tolerance_minutes',
            field=models.PositiveSmallIntegerField(default=60, help_text='لا يُقترَح خصمٌ دونها — كساعة البريك', verbose_name='تسامح الخروج (دقيقة)'),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='presence_tracking_enabled',
            field=models.BooleanField(default=False, verbose_name='تتبّع التواجد في الموقع'),
        ),
    ]
