# Generated by Django 5.2.6 on 2026-09-13 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_builtin_roles_are_system'),
        ('payroll', '0038_presence_tracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='GLAccountMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('component_code', models.CharField(max_length=40, verbose_name='رمز البند')),
                ('name_ar', models.CharField(blank=True, max_length=150, verbose_name='البيان')),
                ('debit_account', models.CharField(blank=True, max_length=40, verbose_name='الحساب المدين')),
                ('credit_account', models.CharField(blank=True, max_length=40, verbose_name='الحساب الدائن')),
                ('is_excluded', models.BooleanField(default=False, verbose_name='مستثنى')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='ملاحظة')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.account', verbose_name='الحساب')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.company', verbose_name='الشركة')),
            ],
            options={
                'verbose_name': 'ربط حساب',
                'verbose_name_plural': 'ربط الحسابات',
                'ordering': ['component_code'],
                'constraints': [models.UniqueConstraint(fields=('company', 'component_code'), name='uq_glmap_company_code')],
            },
        ),
        migrations.CreateModel(
            name='GLTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('code', models.CharField(max_length=40, verbose_name='الرمز')),
                ('name_ar', models.CharField(max_length=120, verbose_name='القالب')),
                ('target_system', models.CharField(blank=True, help_text='أودو · SAP · مايكروسوفت — للتذكير لا للمنطق', max_length=80, verbose_name='النظام المستهدَف')),
                ('grouping', models.CharField(choices=[('company', 'قيدٌ واحد للمسير'), ('department', 'بالإدارة'), ('cost_center', 'بمركز التكلفة'), ('employee', 'سطرٌ لكل موظف')], default='company', max_length=15, verbose_name='مستوى التجميع')),
                ('columns', models.JSONField(default=list, verbose_name='الأعمدة')),
                ('delimiter', models.CharField(default=',', max_length=3, verbose_name='الفاصل')),
                ('encoding', models.CharField(default='utf-8-sig', max_length=20)),
                ('date_format', models.CharField(default='%Y-%m-%d', max_length=20)),
                ('include_header', models.BooleanField(default=True, verbose_name='سطر العناوين')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.account', verbose_name='الحساب')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.company', verbose_name='الشركة')),
            ],
            options={
                'verbose_name': 'قالب قيد محاسبيّ',
                'verbose_name_plural': 'قوالب القيد المحاسبيّ',
                'ordering': ['name_ar'],
                'constraints': [models.UniqueConstraint(fields=('company', 'code'), name='uq_gltemplate_company_code')],
            },
        ),
    ]
