# Generated by Django 5.2.6 on 2026-09-14 08:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0040_gl_rls'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollsettings',
            name='payroll_cutoff_day',
            field=models.PositiveSmallIntegerField(default=0, help_text='٠ = الشهر التقويميّ · ٢١ = من ٢٢ الشهر الماضي إلى ٢١ الحاليّ. ⚠️ وأقصاه ٢٨ فشهر فبراير', validators=[django.core.validators.MaxValueValidator(28)], verbose_name='يوم الاقتطاع'),
        ),
    ]
