# Generated by Django 5.2.6 on 2026-09-14 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0041_cutoff_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollsettings',
            name='retro_max_age_days',
            field=models.PositiveSmallIntegerField(default=365, verbose_name='أقصى قِدَم للأثر الرجعيّ (يومًا)'),
        ),
    ]
