# Generated by Django 5.2.6 on 2026-09-16 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0042_retro_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retroadjustment',
            name='source',
            field=models.CharField(choices=[('attendance_fix', 'تصحيح بصمة'), ('leave', 'إجازة بأثر رجعي'), ('overtime', 'عمل إضافي متأخر'), ('salary', 'تغيير راتب بأثر رجعي'), ('other', 'تعديل آخر')], max_length=20, verbose_name='المصدر'),
        ),
    ]
