# Generated by Django 5.2.6 on 2026-09-21 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0064_invite_existing_free_only'),
        ('employees', '0031_training_rls'),
        ('payroll', '0043_retro_salary_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollExclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('scope', models.CharField(choices=[('run', 'هذا المسير فقط'), ('until_revoked', 'حتى يُعاد يدويًّا')], max_length=20, verbose_name='النطاق')),
                ('reason', models.CharField(max_length=255, verbose_name='السبب')),
                ('excluded_by_person_id', models.BigIntegerField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='أُعيد في')),
                ('revoked_by_person_id', models.BigIntegerField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.account', verbose_name='الحساب')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.company', verbose_name='الشركة')),
                ('employment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_exclusions', to='employees.employment', verbose_name='الموظف')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exclusions', to='payroll.payrollrun', verbose_name='المسير')),
            ],
            options={
                'verbose_name': 'استبعاد من المسير',
                'verbose_name_plural': 'الاستبعادات من المسير',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['company', 'scope', 'revoked_at'], name='idx_excl_company_scope'), models.Index(fields=['run', 'revoked_at'], name='idx_excl_run')],
            },
        ),
    ]
