# Generated by Django 5.2.6 on 2026-09-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0045_exclusion_rls'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollsettings',
            name='auto_attendance',
            field=models.BooleanField(default=True, help_text='موقوف: الحضور يُدخَل يدويًّا — للشركات التي لا تستعمل البصمة', verbose_name='احتساب الحضور تلقائيًّا'),
        ),
    ]
