# Generated by Django 5.2.6 on 2026-09-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0046_payrollsettings_auto_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslipline',
            name='explanation_en',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='شرح الاحتساب بالإنجليزية'),
        ),
    ]
