# Generated by Django 5.2.6 on 2026-09-24 15:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0048_missing_components'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollsettings',
            name='payroll_start_month',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(12)], verbose_name='شهر أول مسير'),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='payroll_start_year',
            field=models.PositiveSmallIntegerField(default=0, help_text='٠ = بلا حدّ · وإلا فلا مسير قبل هذا الشهر', verbose_name='سنة أول مسير'),
        ),
    ]
