# Generated by Django 5.2.6 on 2026-09-24 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0064_invite_existing_free_only'),
        ('employees', '0031_training_rls'),
        ('payroll', '0049_payroll_start_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollsettings',
            name='attendance_deduction_mode',
            field=models.CharField(choices=[('auto', 'آليّ'), ('manual', 'يدويّ — بقرار الموارد')], default='auto', max_length=10, verbose_name='خصم البصمات'),
        ),
        migrations.CreateModel(
            name='AttendanceDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('period_year', models.PositiveSmallIntegerField(verbose_name='السنة')),
                ('period_month', models.PositiveSmallIntegerField(verbose_name='الشهر')),
                ('work_date', models.DateField(db_index=True, verbose_name='اليوم')),
                ('kind', models.CharField(choices=[('absence', 'غياب'), ('late', 'تأخير'), ('shortfall', 'نقص ساعات')], max_length=12, verbose_name='النوع')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='المقدار')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='المبلغ')),
                ('explanation', models.CharField(blank=True, max_length=255, verbose_name='البيان')),
                ('status', models.CharField(choices=[('pending', 'بانتظار القرار'), ('applied', 'مخصوم'), ('waived', 'معفى')], db_index=True, default='pending', max_length=12, verbose_name='الحالة')),
                ('decision_note', models.CharField(blank=True, max_length=255, verbose_name='سبب القرار')),
                ('decided_by_person_id', models.BigIntegerField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.account', verbose_name='الحساب')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.company', verbose_name='الشركة')),
                ('employment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_deductions', to='employees.employment', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'خصم بصمة',
                'verbose_name_plural': 'خصومات البصمات',
                'ordering': ['-work_date', 'employment_id'],
                'indexes': [models.Index(fields=['company', 'period_year', 'period_month', 'status'], name='payroll_att_company_e74055_idx')],
                'constraints': [models.UniqueConstraint(fields=('employment', 'work_date', 'kind'), name='uq_attendance_deduction_per_day')],
            },
        ),
    ]
