# Generated by Django 5.2.6 on 2026-09-27 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0051_attendance_deduction_rls'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancededuction',
            name='settled_in_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settled_deductions', to='payroll.payrollrun', verbose_name='سُوّي في مسير'),
        ),
    ]
