# Generated by Django 5.2.6 on 2026-08-30 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0010_billing_inherit_base'),
        ('organization', '0002_org_rls'),
        ('payroll', '0004_company_bears_gosi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('first_name_ar', models.CharField(max_length=80, verbose_name='الاسم الأول')),
                ('father_name_ar', models.CharField(blank=True, max_length=80, verbose_name='اسم الأب')),
                ('grandfather_name_ar', models.CharField(blank=True, max_length=80, verbose_name='اسم الجد')),
                ('family_name_ar', models.CharField(max_length=80, verbose_name='اسم العائلة')),
                ('full_name_en', models.CharField(blank=True, help_text='كما في الجواز أو الإقامة حرفيًا', max_length=200, verbose_name='الاسم بالإنجليزية')),
                ('gender', models.CharField(choices=[('male', 'ذكر'), ('female', 'أنثى')], max_length=10, verbose_name='الجنس')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد')),
                ('birth_date_hijri', models.CharField(blank=True, max_length=10, verbose_name='الميلاد هجريًا')),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'أعزب'), ('married', 'متزوج'), ('divorced', 'مطلق'), ('widowed', 'أرمل')], max_length=20, verbose_name='الحالة الاجتماعية')),
                ('nationality_code', models.CharField(help_text='رمز الدولة ISO 3166-1 alpha-2 — SA للسعودية', max_length=2, verbose_name='الجنسية')),
                ('id_type', models.CharField(choices=[('national_id', 'هوية وطنية'), ('iqama', 'إقامة'), ('border_no', 'رقم حدود'), ('passport', 'جواز سفر'), ('gcc_id', 'هوية خليجية')], max_length=20, verbose_name='نوع الهوية')),
                ('id_number', models.CharField(max_length=20, verbose_name='رقم الهوية')),
                ('id_expiry_date', models.DateField(blank=True, null=True, verbose_name='انتهاء الهوية')),
                ('id_expiry_hijri', models.CharField(blank=True, max_length=10, verbose_name='الانتهاء هجريًا')),
                ('passport_number', models.CharField(blank=True, max_length=20, verbose_name='رقم الجواز')),
                ('passport_expiry_date', models.DateField(blank=True, null=True, verbose_name='انتهاء الجواز')),
                ('border_number', models.CharField(blank=True, max_length=20, verbose_name='رقم الحدود')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('mobile_e164', models.CharField(blank=True, help_text='بصيغة دولية +9665… — مفتاح التعريف في واتساب', max_length=20, verbose_name='الجوال')),
                ('preferred_locale', models.CharField(choices=[('ar', 'العربية'), ('en', 'English'), ('ur', 'اردو')], default='ar', max_length=5, verbose_name='اللغة المفضلة')),
                ('gosi_scheme_code', models.CharField(blank=True, help_text='يتحدد بتاريخ أول اشتراك للفرد وعمره حينها. فارغ = غير مسجّل في التأمينات لدى أي جهة. لا يتغير بتغير جهة العمل.', max_length=30, null=True, verbose_name='النظام التأميني')),
                ('gosi_first_subscription_date', models.DateField(blank=True, null=True, verbose_name='تاريخ أول اشتراك')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.account', verbose_name='الحساب')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person', to=settings.AUTH_USER_MODEL, verbose_name='حساب الدخول')),
            ],
            options={
                'verbose_name': 'شخص',
                'verbose_name_plural': 'الأشخاص',
                'ordering': ['family_name_ar', 'first_name_ar'],
            },
        ),
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('employee_no', models.CharField(max_length=30, verbose_name='الرقم الوظيفي')),
                ('employment_type', models.CharField(choices=[('primary', 'أساسي'), ('secondary', 'ثانوي'), ('seconded', 'منتدب'), ('board_member', 'عضو مجلس')], default='primary', max_length=20, verbose_name='نوع الارتباط')),
                ('work_ratio', models.DecimalField(decimal_places=3, default=1, help_text='1.000 = دوام كامل', max_digits=4, verbose_name='نسبة الدوام')),
                ('join_date', models.DateField(help_text='المباشرة في هذه الشركة — للعقد والوثائق الرسمية', verbose_name='تاريخ المباشرة')),
                ('service_start_date', models.DateField(blank=True, help_text='أساس مكافأة نهاية الخدمة والإجازات. يساوي تاريخ المباشرة عادةً، ويسبقه عند النقل باستمرارية الخدمة داخل المجموعة (ق-14)', null=True, verbose_name='بداية الخدمة المحتسبة')),
                ('contract_type', models.CharField(choices=[('fixed_term', 'محدد المدة'), ('indefinite', 'غير محدد المدة')], default='indefinite', max_length=20, verbose_name='نوع العقد')),
                ('contract_start_date', models.DateField(blank=True, null=True, verbose_name='بداية العقد')),
                ('contract_end_date', models.DateField(blank=True, null=True, verbose_name='نهاية العقد')),
                ('probation_days', models.PositiveSmallIntegerField(default=90, help_text='90 يومًا، وتُمدَّد إلى 180 باتفاق كتابي', verbose_name='فترة التجربة (أيام)')),
                ('probation_end_date', models.DateField(blank=True, null=True, verbose_name='انتهاء التجربة')),
                ('status', models.CharField(choices=[('active', 'على رأس العمل'), ('on_leave', 'في إجازة'), ('suspended', 'موقوف'), ('terminated', 'منتهية خدمته'), ('transferred', 'منقول داخل المجموعة')], db_index=True, default='active', max_length=20, verbose_name='الحالة')),
                ('termination_date', models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء الخدمة')),
                ('termination_reason', models.CharField(blank=True, help_text='من قائمة الوزارة الرسمية (ق-26)', max_length=40, verbose_name='سبب انتهاء الخدمة')),
                ('transfer_mode', models.CharField(blank=True, choices=[('settled', 'تصفية ثم نقل'), ('continued', 'استمرار احتساب الخدمة')], max_length=20, verbose_name='نمط النقل')),
                ('is_gosi_registered', models.BooleanField(db_index=True, default=False, verbose_name='مسجّل في التأمينات')),
                ('gosi_establishment_no', models.CharField(blank=True, max_length=20, verbose_name='رقم منشأة التأمينات')),
                ('gosi_registered_at', models.DateField(blank=True, null=True, verbose_name='تاريخ التسجيل')),
                ('gosi_declared_wage', models.DecimalField(blank=True, decimal_places=2, help_text='قد يخالف الأجر المدفوع فعلًا — النظام يعكس الواقع', max_digits=12, null=True, verbose_name='الأجر المسجّل لدى التأمينات')),
                ('is_mol_registered', models.BooleanField(db_index=True, default=False, help_text='نطاقات تحتسب المسجّلين في قوى فقط', verbose_name='مسجّل في قوى')),
                ('mol_contract_no', models.CharField(blank=True, max_length=40, verbose_name='رقم عقد قوى')),
                ('mol_registered_at', models.DateField(blank=True, null=True, verbose_name='تاريخ التسجيل في قوى')),
                ('include_in_wps', models.BooleanField(db_index=True, default=False, verbose_name='مُدرج في حماية الأجور')),
                ('registration_note', models.TextField(blank=True, help_text='سبب عدم التسجيل — للتقارير الداخلية لا للحجب', verbose_name='ملاحظة التسجيل')),
                ('gosi_borne_by_company', models.BooleanField(blank=True, help_text='فارغ = يتبع إعداد الشركة. يُضبط لاستثناء موظف بعينه', null=True, verbose_name='الشركة تتحمل حصته من التأمينات')),
                ('bank_code', models.CharField(blank=True, max_length=20, verbose_name='رمز البنك')),
                ('iban', models.CharField(blank=True, max_length=24, verbose_name='الآيبان')),
                ('payment_method', models.CharField(choices=[('bank', 'تحويل بنكي'), ('cash', 'نقدًا'), ('cheque', 'شيك')], default='bank', max_length=20, verbose_name='طريقة الصرف')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.account', verbose_name='الحساب')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employments', to='organization.branch', verbose_name='الفرع')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.company', verbose_name='الشركة')),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employments', to='organization.costcenter', verbose_name='مركز التكلفة')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employments', to='organization.department', verbose_name='القسم')),
                ('direct_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='employees.employment', verbose_name='المدير المباشر')),
                ('job_title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employments', to='organization.jobtitle', verbose_name='المسمى الوظيفي')),
                ('previous_employment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_employments', to='employees.employment', verbose_name='الارتباط السابق')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employments', to='employees.person', verbose_name='الشخص')),
            ],
            options={
                'verbose_name': 'ارتباط وظيفي',
                'verbose_name_plural': 'الارتباطات الوظيفية',
                'ordering': ['employee_no'],
            },
        ),
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('effective_from', models.DateField(db_index=True, verbose_name='سريان من')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='سريان إلى')),
                ('reason', models.CharField(choices=[('hiring', 'تعيين'), ('annual_raise', 'علاوة سنوية'), ('promotion', 'ترقية'), ('adjustment', 'تعديل'), ('transfer', 'نقل داخل المجموعة'), ('contract_renewal', 'تجديد عقد')], default='hiring', max_length=30, verbose_name='السبب')),
                ('note', models.TextField(blank=True, verbose_name='ملاحظة')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.account', verbose_name='الحساب')),
                ('approved_by_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_salary_structures', to='employees.person', verbose_name='المعتمِد')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.company', verbose_name='الشركة')),
                ('employment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_structures', to='employees.employment', verbose_name='الارتباط الوظيفي')),
            ],
            options={
                'verbose_name': 'هيكل راتب',
                'verbose_name_plural': 'هياكل الرواتب',
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='SalaryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salary_lines', to='payroll.paycomponent', verbose_name='المكوّن')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='employees.salarystructure')),
            ],
            options={
                'verbose_name': 'بند راتب',
                'verbose_name_plural': 'بنود الراتب',
            },
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['account', 'id_number'], name='employees_p_account_6ab071_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['account', 'mobile_e164'], name='employees_p_account_e13c28_idx'),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.UniqueConstraint(fields=('account', 'id_type', 'id_number'), name='uq_person_identity'),
        ),
        migrations.AddIndex(
            model_name='employment',
            index=models.Index(fields=['company', 'status'], name='employees_e_company_98c6a1_idx'),
        ),
        migrations.AddIndex(
            model_name='employment',
            index=models.Index(fields=['person'], name='employees_e_person__1c31db_idx'),
        ),
        migrations.AddConstraint(
            model_name='employment',
            constraint=models.UniqueConstraint(fields=('company', 'employee_no'), name='uq_employment_no_per_company'),
        ),
        migrations.AddConstraint(
            model_name='employment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('company', 'person'), name='uq_active_employment_per_person_company'),
        ),
        migrations.AddConstraint(
            model_name='salarystructure',
            constraint=models.UniqueConstraint(fields=('employment', 'effective_from'), name='uq_salary_structure_per_date'),
        ),
        migrations.AddConstraint(
            model_name='salaryline',
            constraint=models.UniqueConstraint(fields=('structure', 'component'), name='uq_salary_line_per_component'),
        ),
    ]
