# Generated by Django 5.2.6 on 2026-08-30 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_billing_inherit_base'),
        ('employees', '0002_employees_rls'),
        ('leaves', '0003_leaves_rls'),
        ('payroll', '0012_assets_advances_documents'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('advance_no', models.CharField(max_length=30, verbose_name='رقم السلفة')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='مبلغ السلفة')),
                ('reason', models.TextField(blank=True, verbose_name='السبب')),
                ('repayment_method', models.CharField(choices=[('equal', 'أقساط شهرية متساوية'), ('manual', 'مبلغ يحدده مدير الموارد شهريًا'), ('lump_sum', 'دفعة واحدة في شهر محدد')], default='equal', max_length=20, verbose_name='طريقة السداد')),
                ('installments_count', models.PositiveSmallIntegerField(default=1, help_text='عند الأقساط المتساوية', verbose_name='عدد الأقساط')),
                ('installment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='قيمة القسط')),
                ('start_year', models.PositiveSmallIntegerField(verbose_name='سنة بدء السداد')),
                ('start_month', models.PositiveSmallIntegerField(verbose_name='شهر بدء السداد')),
                ('repaid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='المسدَّد')),
                ('status', models.CharField(choices=[('pending', 'قيد الاعتماد'), ('active', 'قيد السداد'), ('settled', 'مسدَّدة'), ('cancelled', 'ملغاة'), ('written_off', 'مشطوبة')], db_index=True, default='pending', max_length=20, verbose_name='الحالة')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الاعتماد')),
                ('settled_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت السداد الكامل')),
                ('note', models.TextField(blank=True, verbose_name='ملاحظة')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.account', verbose_name='الحساب')),
                ('approved_by_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_advances', to='employees.person')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.company', verbose_name='الشركة')),
                ('employment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advances', to='employees.employment', verbose_name='الموظف')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advances', to='leaves.request', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'سلفة',
                'verbose_name_plural': 'السلف',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdvanceInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('period_year', models.PositiveSmallIntegerField(verbose_name='السنة')),
                ('period_month', models.PositiveSmallIntegerField(verbose_name='الشهر')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ')),
                ('is_deducted', models.BooleanField(default=False, verbose_name='خُصم فعلًا')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='ملاحظة')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.account', verbose_name='الحساب')),
                ('advance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='employees.advance')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.company', verbose_name='الشركة')),
                ('payslip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advance_installments', to='payroll.payslip', verbose_name='القسيمة')),
            ],
            options={
                'verbose_name': 'قسط سلفة',
                'verbose_name_plural': 'أقساط السلف',
                'ordering': ['advance', 'period_year', 'period_month'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('asset_no', models.CharField(max_length=40, verbose_name='رقم العهدة')),
                ('name_ar', models.CharField(max_length=200, verbose_name='الوصف')),
                ('category', models.CharField(choices=[('device', 'جهاز'), ('vehicle', 'مركبة'), ('phone', 'هاتف'), ('tool', 'أداة'), ('uniform', 'زي'), ('card', 'بطاقة'), ('other', 'أخرى')], default='other', max_length=20, verbose_name='التصنيف')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='الرقم التسلسلي')),
                ('value', models.DecimalField(decimal_places=2, default=0, help_text='تُخصم من المخالصة عند عدم الإرجاع', max_digits=12, verbose_name='القيمة')),
                ('assigned_date', models.DateField(verbose_name='تاريخ التسليم')),
                ('expected_return_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الإرجاع المتوقع')),
                ('returned_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الإرجاع')),
                ('status', models.CharField(choices=[('assigned', 'بعهدة الموظف'), ('returned', 'مُرجَعة'), ('damaged', 'تالفة'), ('lost', 'مفقودة'), ('deducted', 'خُصمت قيمتها')], db_index=True, default='assigned', max_length=20, verbose_name='الحالة')),
                ('condition_note', models.TextField(blank=True, verbose_name='ملاحظة الحالة')),
                ('handover_document', models.CharField(blank=True, max_length=500, verbose_name='مستند التسليم')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.account', verbose_name='الحساب')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.company', verbose_name='الشركة')),
                ('employment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='employees.employment', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'عهدة',
                'verbose_name_plural': 'العهد',
                'ordering': ['-assigned_date'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('document_type', models.CharField(choices=[('iqama', 'إقامة'), ('passport', 'جواز سفر'), ('national_id', 'هوية وطنية'), ('work_permit', 'رخصة عمل'), ('driving_license', 'رخصة قيادة'), ('health_cert', 'شهادة صحية'), ('qualification', 'مؤهل علمي'), ('contract', 'عقد عمل'), ('medical_insurance', 'تأمين طبي'), ('other', 'أخرى')], max_length=30, verbose_name='النوع')),
                ('document_number', models.CharField(blank=True, max_length=60, verbose_name='الرقم')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الإصدار')),
                ('expiry_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('expiry_hijri', models.CharField(blank=True, max_length=10, verbose_name='الانتهاء هجريًا')),
                ('issuing_authority', models.CharField(blank=True, max_length=150, verbose_name='جهة الإصدار')),
                ('file_url', models.CharField(blank=True, max_length=500, verbose_name='الملف')),
                ('alert_days_before', models.PositiveSmallIntegerField(default=60, verbose_name='التنبيه قبل (أيام)')),
                ('note', models.TextField(blank=True, verbose_name='ملاحظة')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.account', verbose_name='الحساب')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.company', verbose_name='الشركة')),
                ('employment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='employees.employment', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'وثيقة موظف',
                'verbose_name_plural': 'وثائق الموظفين',
                'ordering': ['expiry_date'],
            },
        ),
        migrations.AddIndex(
            model_name='advance',
            index=models.Index(fields=['employment', 'status'], name='employees_a_employm_8298c6_idx'),
        ),
        migrations.AddIndex(
            model_name='advance',
            index=models.Index(fields=['company', 'status'], name='employees_a_company_0b3c0b_idx'),
        ),
        migrations.AddConstraint(
            model_name='advance',
            constraint=models.UniqueConstraint(fields=('company', 'advance_no'), name='uq_advance_no_per_company'),
        ),
        migrations.AddConstraint(
            model_name='advance',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='chk_advance_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='advanceinstallment',
            constraint=models.UniqueConstraint(fields=('advance', 'period_year', 'period_month'), name='uq_installment_per_period'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['employment', 'status'], name='employees_a_employm_ecf612_idx'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(fields=('company', 'asset_no'), name='uq_asset_no_per_company'),
        ),
        migrations.AddIndex(
            model_name='employeedocument',
            index=models.Index(fields=['company', 'expiry_date'], name='employees_e_company_303165_idx'),
        ),
        migrations.AddIndex(
            model_name='employeedocument',
            index=models.Index(fields=['employment', 'document_type'], name='employees_e_employm_093295_idx'),
        ),
    ]
