# Generated by Django 5.2.6 on 2026-09-01 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_storage_limit'),
        ('attendance', '0004_worksites_rls'),
        ('employees', '0004_assets_rls'),
    ]

    operations = [
        migrations.AddField(
            model_name='employment',
            name='primary_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_employments', to='attendance.worksite', verbose_name='موقع العمل'),
        ),
        migrations.CreateModel(
            name='Dependent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('full_name_ar', models.CharField(max_length=180, verbose_name='الاسم')),
                ('full_name_en', models.CharField(blank=True, max_length=180, verbose_name='بالإنجليزية')),
                ('relation', models.CharField(choices=[('spouse', 'زوج/زوجة'), ('son', 'ابن'), ('daughter', 'ابنة'), ('father', 'أب'), ('mother', 'أم'), ('brother', 'أخ'), ('sister', 'أخت'), ('other', 'أخرى')], max_length=20, verbose_name='صلة القرابة')),
                ('id_number', models.CharField(blank=True, max_length=20, verbose_name='رقم الهوية')),
                ('id_expiry_date', models.DateField(blank=True, null=True, verbose_name='انتهاء الهوية')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد')),
                ('nationality_code', models.CharField(blank=True, max_length=2, verbose_name='الجنسية')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='ملاحظة')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.account', verbose_name='الحساب')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='employees.person', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'تابع',
                'verbose_name_plural': 'التابعون',
                'ordering': ['relation', 'full_name_ar'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('full_name_ar', models.CharField(max_length=180, verbose_name='الاسم')),
                ('relation', models.CharField(max_length=60, verbose_name='الصلة')),
                ('mobile', models.CharField(max_length=20, verbose_name='الجوال')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='هاتف آخر')),
                ('is_primary', models.BooleanField(default=False, verbose_name='الأساسي')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.account', verbose_name='الحساب')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='employees.person', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'رقم طوارئ',
                'verbose_name_plural': 'أرقام الطوارئ',
                'ordering': ['-is_primary', 'full_name_ar'],
            },
        ),
        migrations.CreateModel(
            name='JobGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('code', models.CharField(max_length=20, verbose_name='الرمز')),
                ('name_ar', models.CharField(max_length=120, verbose_name='الاسم')),
                ('name_en', models.CharField(blank=True, max_length=120, verbose_name='بالإنجليزية')),
                ('level', models.IntegerField(default=0, verbose_name='المستوى')),
                ('min_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='أدنى راتب')),
                ('max_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='أعلى راتب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.account', verbose_name='الحساب')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.company', verbose_name='الشركة')),
            ],
            options={
                'verbose_name': 'مرتبة وظيفية',
                'verbose_name_plural': 'المراتب الوظيفية',
                'ordering': ['level', 'name_ar'],
            },
        ),
        migrations.AddField(
            model_name='employment',
            name='job_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employments', to='employees.jobgrade', verbose_name='المرتبة الوظيفية'),
        ),
        migrations.CreateModel(
            name='JobStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('code', models.CharField(max_length=20, verbose_name='الرمز')),
                ('name_ar', models.CharField(max_length=120, verbose_name='الاسم')),
                ('step_number', models.IntegerField(default=0, verbose_name='رقم الدرجة')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='الراتب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.account', verbose_name='الحساب')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.company', verbose_name='الشركة')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='employees.jobgrade', verbose_name='المرتبة')),
            ],
            options={
                'verbose_name': 'درجة وظيفية',
                'verbose_name_plural': 'الدرجات الوظيفية',
                'ordering': ['step_number'],
            },
        ),
        migrations.AddField(
            model_name='employment',
            name='job_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employments', to='employees.jobstep', verbose_name='الدرجة الوظيفية'),
        ),
        migrations.AddConstraint(
            model_name='jobgrade',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uniq_job_grade'),
        ),
        migrations.AddConstraint(
            model_name='jobstep',
            constraint=models.UniqueConstraint(fields=('grade', 'code'), name='uniq_job_step'),
        ),
    ]
