# Generated by Django 5.2.6 on 2026-09-04 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_accountmembership_is_founding_owner_and_more'),
        ('employees', '0006_profile_rls'),
        ('organization', '0002_org_rls'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('change_type', models.CharField(choices=[('promotion', 'ترقية'), ('demotion', 'تنزيل'), ('transfer', 'نقل وظيفي'), ('dismissal', 'فصل')], max_length=20, verbose_name='نوع التغيير')),
                ('effective_from', models.DateField(verbose_name='يسري من')),
                ('new_job_title', models.CharField(blank=True, max_length=120, verbose_name='المسمّى الجديد')),
                ('new_role_code', models.CharField(blank=True, max_length=30, verbose_name='الدور الجديد')),
                ('dismissal_reason', models.CharField(blank=True, max_length=60, verbose_name='سبب الفصل')),
                ('old_job_title', models.CharField(blank=True, max_length=120)),
                ('old_department_id', models.BigIntegerField(blank=True, null=True)),
                ('old_direct_manager_id', models.BigIntegerField(blank=True, null=True)),
                ('old_role_code', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(choices=[('pending', 'بانتظار الاعتماد'), ('approved', 'معتمد'), ('rejected', 'مرفوض'), ('cancelled', 'ملغى')], db_index=True, default='pending', max_length=20, verbose_name='الحالة')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='ملاحظة')),
                ('created_by_person_id', models.BigIntegerField(blank=True, null=True)),
                ('decided_by_person_id', models.BigIntegerField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.CharField(blank=True, max_length=300)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.account', verbose_name='الحساب')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.company', verbose_name='الشركة')),
                ('employment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_changes', to='employees.employment', verbose_name='الموظف')),
                ('new_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.department', verbose_name='الإدارة الجديدة')),
                ('new_direct_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='employees.employment', verbose_name='المدير المباشر الجديد')),
                ('successor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='employees.employment', verbose_name='من يخلفه في موقعه')),
            ],
            options={
                'verbose_name': 'تغيير وظيفي',
                'verbose_name_plural': 'التغييرات الوظيفية',
                'ordering': ['-effective_from', '-id'],
                'indexes': [models.Index(fields=['employment', '-effective_from'], name='employees_j_employm_3014ab_idx'), models.Index(fields=['status', 'company'], name='employees_j_status_a5ddb7_idx')],
            },
        ),
    ]
