# Generated by Django 5.2.6 on 2026-09-04 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_jobchange_rls'),
        ('organization', '0002_org_rls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobchange',
            name='old_job_title',
        ),
        migrations.AddField(
            model_name='jobchange',
            name='old_job_title_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobchange',
            name='new_job_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.jobtitle', verbose_name='المسمّى الجديد'),
        ),
    ]
