# Generated by Django 5.2.6 on 2026-09-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_remove_jobchange_old_job_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employment',
            name='termination_pending_from',
            field=models.DateField(blank=True, help_text='تاريخ سريان الفصل المعتمَد — الخدمة تنتهي بإتمام المخالصة وإخلاء الطرف', null=True, verbose_name='إنهاء خدمة قيد الإنجاز من'),
        ),
    ]
