# Generated by Django 5.2.6 on 2026-09-07 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_employment_termination_pending_from'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='border_number',
        ),
    ]
