# Generated by Django 5.2.6 on 2026-09-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_remove_person_border_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='employment',
            name='allow_mobile_punch',
            field=models.BooleanField(default=True, verbose_name='بصمة الجوال'),
        ),
    ]
