# Generated by Django 5.2.6 on 2026-09-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_employment_allow_mobile_punch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employment',
            name='allow_mobile_punch',
            field=models.BooleanField(blank=True, default=None, help_text='فارغ = يتبع فترة العمل ثم الشركة', null=True, verbose_name='بصمة الجوال'),
        ),
    ]
