# Generated by Django 5.2.6 on 2026-09-09 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_plan_platform_write'),
        ('employees', '0013_alter_employment_allow_mobile_punch'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViolationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('code', models.CharField(max_length=30, verbose_name='الرمز')),
                ('name_ar', models.CharField(max_length=255, verbose_name='المخالفة')),
                ('name_en', models.CharField(blank=True, max_length=255, verbose_name='بالإنجليزية')),
                ('category', models.CharField(choices=[('attendance', 'مخالفات المواعيد'), ('work_org', 'مخالفات تنظيم العمل'), ('conduct', 'مخالفات السلوك'), ('safety', 'مخالفات السلامة'), ('other', 'أخرى')], default='other', max_length=20, verbose_name='التصنيف')),
                ('reset_days', models.PositiveSmallIntegerField(default=180, help_text='بعدها تُعامَل المخالفة معاملة الأولى', verbose_name='مدّة سقوط التكرار (يومًا)')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّلة')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.account', verbose_name='الحساب')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.company', verbose_name='الشركة')),
            ],
            options={
                'verbose_name': 'بند لائحة الجزاءات',
                'verbose_name_plural': 'لائحة الجزاءات',
                'ordering': ['category', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PenaltyDegree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurrence', models.PositiveSmallIntegerField(help_text='1 = المرّة الأولى', verbose_name='التكرار')),
                ('kind', models.CharField(choices=[('warning', 'إنذار كتابي'), ('wage_deduction', 'خصم من الأجر'), ('suspension', 'إيقاف عن العمل بلا أجر'), ('bonus_deprivation', 'حرمان من علاوة'), ('promotion_delay', 'تأجيل ترقية'), ('dismissal', 'الفصل')], max_length=25, verbose_name='الجزاء')),
                ('days', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='الأيام')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='ملاحظة')),
                ('violation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='degrees', to='employees.violationtype', verbose_name='المخالفة')),
            ],
            options={
                'verbose_name': 'درجة جزاء',
                'verbose_name_plural': 'درجات الجزاءات',
                'ordering': ['occurrence'],
            },
        ),
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('occurred_on', models.DateField(db_index=True, verbose_name='تاريخ المخالفة')),
                ('occurrence', models.PositiveSmallIntegerField(default=1, help_text='يُحتسب تلقائيًّا من سوابقه خلال مدّة السقوط', verbose_name='التكرار')),
                ('kind', models.CharField(choices=[('warning', 'إنذار كتابي'), ('wage_deduction', 'خصم من الأجر'), ('suspension', 'إيقاف عن العمل بلا أجر'), ('bonus_deprivation', 'حرمان من علاوة'), ('promotion_delay', 'تأجيل ترقية'), ('dismissal', 'الفصل')], max_length=25, verbose_name='الجزاء')),
                ('days', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='الأيام')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='المبلغ المخصوم')),
                ('description', models.TextField(blank=True, verbose_name='وصف الواقعة')),
                ('employee_statement', models.TextField(blank=True, verbose_name='إفادة الموظف')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('issued', 'موقَّع'), ('objected', 'متظلَّم منه'), ('cancelled', 'ملغى')], db_index=True, default='draft', max_length=20, verbose_name='الحالة')),
                ('issued_by_person_id', models.BigIntegerField(blank=True, null=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('deducted_in_run_id', models.BigIntegerField(blank=True, null=True)),
                ('cancelled_reason', models.CharField(blank=True, max_length=255, verbose_name='سبب الإلغاء')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.account', verbose_name='الحساب')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.company', verbose_name='الشركة')),
                ('employment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='penalties', to='employees.employment', verbose_name='الموظف')),
                ('violation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='penalties', to='employees.violationtype', verbose_name='المخالفة')),
            ],
            options={
                'verbose_name': 'جزاء',
                'verbose_name_plural': 'الجزاءات',
                'ordering': ['-occurred_on', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='violationtype',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uq_violation_company_code'),
        ),
        migrations.AddConstraint(
            model_name='penaltydegree',
            constraint=models.UniqueConstraint(fields=('violation', 'occurrence'), name='uq_degree_violation_occurrence'),
        ),
        migrations.AddIndex(
            model_name='penalty',
            index=models.Index(fields=['employment', 'status'], name='idx_penalty_emp_status'),
        ),
        migrations.AddIndex(
            model_name='penalty',
            index=models.Index(fields=['company', 'occurred_on'], name='idx_penalty_company_date'),
        ),
    ]
