# Generated by Django 5.2.6 on 2026-09-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0015_penalties_rls'),
    ]

    operations = [
        migrations.AddField(
            model_name='penalty',
            name='apply_deduction',
            field=models.BooleanField(default=True, verbose_name='طُبّق الخصم'),
        ),
        migrations.AddField(
            model_name='violationtype',
            name='financial_effect',
            field=models.BooleanField(default=True, help_text='مطفأ = يُوثَّق الجزاء ولا يُخصم', verbose_name='له أثر ماليّ'),
        ),
    ]
