# Generated by Django 5.2.6 on 2026-09-09 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0016_penalty_optional_deduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='penalty',
            name='count_occurrence',
            field=models.BooleanField(default=True, verbose_name='يُحتسب في التكرار'),
        ),
    ]
