# Generated by Django 5.2.6 on 2026-09-09 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0017_penalty_count_occurrence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violationtype',
            name='reset_days',
            field=models.PositiveSmallIntegerField(default=365, help_text='المادة (٧٣): سنة كاملة من تاريخ الارتكاب', verbose_name='مدّة سقوط التكرار (يومًا)'),
        ),
    ]
