# Generated by Django 5.2.6 on 2026-09-11 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_builtin_roles_are_system'),
        ('employees', '0018_reset_days_one_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('number', models.PositiveSmallIntegerField(verbose_name='رقم النسخة')),
                ('effective_from', models.DateField(db_index=True, verbose_name='سريان من')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='سبب التنقيح')),
                ('is_active', models.BooleanField(default=True, help_text='مطفأ = نسخةٌ سابقة تُحفظ للماضي', verbose_name='سارية')),
                ('created_by_person_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'نسخة لائحة الجزاءات',
                'verbose_name_plural': 'نسخ لائحة الجزاءات',
                'ordering': ['-effective_from', '-number'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='violationtype',
            name='uq_violation_company_code',
        ),
        migrations.AddField(
            model_name='penalty',
            name='policy_version_no',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='نسخة اللائحة'),
        ),
        migrations.AddField(
            model_name='policyversion',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.account', verbose_name='الحساب'),
        ),
        migrations.AddField(
            model_name='policyversion',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.company', verbose_name='الشركة'),
        ),
        migrations.AddField(
            model_name='violationtype',
            name='policy_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='employees.policyversion', verbose_name='نسخة اللائحة'),
        ),
        migrations.AddConstraint(
            model_name='violationtype',
            constraint=models.UniqueConstraint(fields=('company', 'policy_version', 'code'), name='uq_violation_version_code'),
        ),
        migrations.AddConstraint(
            model_name='policyversion',
            constraint=models.UniqueConstraint(fields=('company', 'number'), name='uq_polver_company_number'),
        ),
    ]
