# Generated by Django 5.2.6 on 2026-09-11 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_builtin_roles_are_system'),
        ('employees', '0020_polver_rls_and_backfill'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('name_ar', models.CharField(max_length=60, verbose_name='الوسم')),
                ('color', models.CharField(blank=True, help_text='teal · copper · ok · danger — أو فارغ', max_length=20, verbose_name='اللون')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='الوصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.account', verbose_name='الحساب')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.company', verbose_name='الشركة')),
            ],
            options={
                'verbose_name': 'وسم موظفين',
                'verbose_name_plural': 'وسوم الموظفين',
                'ordering': ['name_ar'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeTagAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('assigned_by_person_id', models.BigIntegerField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.account', verbose_name='الحساب')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.company', verbose_name='الشركة')),
                ('employment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_assignments', to='employees.employment')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='employees.employeetag')),
            ],
            options={
                'verbose_name': 'إسناد وسم',
                'verbose_name_plural': 'إسنادات الوسوم',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('title', models.CharField(max_length=200, verbose_name='المهمّة')),
                ('description', models.TextField(blank=True, verbose_name='التفاصيل')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الاستحقاق')),
                ('priority', models.CharField(choices=[('low', 'منخفضة'), ('normal', 'عادية'), ('high', 'عالية'), ('urgent', 'عاجلة')], default='normal', max_length=10, verbose_name='الأولوية')),
                ('status', models.CharField(choices=[('open', 'مفتوحة'), ('in_progress', 'قيد التنفيذ'), ('done', 'منجزة'), ('cancelled', 'ملغاة')], db_index=True, default='open', max_length=15, verbose_name='الحالة')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completion_note', models.CharField(blank=True, max_length=255, verbose_name='ملاحظة الإنجاز')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.account', verbose_name='الحساب')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_assigned', to='employees.employment', verbose_name='المُسنِد')),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='employees.employment', verbose_name='المسنَد إليه')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.company', verbose_name='الشركة')),
            ],
            options={
                'verbose_name': 'مهمّة',
                'verbose_name_plural': 'المهامّ',
                'ordering': ['status', 'due_date', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='employeetag',
            constraint=models.UniqueConstraint(fields=('company', 'name_ar'), name='uq_tag_company_name'),
        ),
        migrations.AddConstraint(
            model_name='employeetagassignment',
            constraint=models.UniqueConstraint(fields=('tag', 'employment'), name='uq_tagassign_tag_emp'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assignee', 'status'], name='idx_task_assignee_status'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['company', 'due_date'], name='idx_task_company_due'),
        ),
    ]
