# Generated by Django 5.2.6 on 2026-09-12 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0022_tags_tasks_rls'),
    ]

    operations = [
        migrations.AddField(
            model_name='advance',
            name='auto_deduct',
            field=models.BooleanField(default=True, verbose_name='الخصم المباشر من الراتب'),
        ),
        migrations.AddField(
            model_name='advance',
            name='deduct_paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='advance',
            name='deduct_paused_by_person_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='advance',
            name='deduct_paused_reason',
            field=models.CharField(blank=True, help_text='إلزاميّ عند الإيقاف — فإيقافٌ بلا سبب يُنسى', max_length=255, verbose_name='سبب إيقاف الخصم'),
        ),
    ]
