# Generated by Django 5.2.6 on 2026-09-12 19:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_builtin_roles_are_system'),
        ('employees', '0023_advance_auto_deduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('work_date', models.DateField(db_index=True, verbose_name='اليوم')),
                ('title', models.CharField(max_length=200, verbose_name='النشاط')),
                ('description', models.TextField(blank=True, verbose_name='التفاصيل')),
                ('target_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='العدد المستهدَف')),
                ('unit', models.CharField(blank=True, help_text='معاملة · تقرير · زيارة', max_length=40, verbose_name='الوحدة')),
                ('pay_effect', models.CharField(choices=[('none', 'بلا أثر ماليّ'), ('bonus', 'مكافأة على التحقيق'), ('deduction', 'حسم على التقصير'), ('both', 'مكافأةٌ وحسم')], default='none', max_length=12, verbose_name='الأثر الماليّ')),
                ('pay_basis', models.CharField(choices=[('per_activity', 'مبلغ للنشاط كاملًا'), ('per_unit', 'مبلغ لكل وحدة')], default='per_activity', max_length=15, verbose_name='أساس الاحتساب')),
                ('bonus_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مبلغ المكافأة')),
                ('deduction_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مبلغ الحسم')),
                ('status', models.CharField(choices=[('pending', 'بانتظار الإقرار'), ('done', 'أُنجز'), ('partial', 'أُنجز جزئيًّا'), ('not_done', 'لم يُنجَز')], db_index=True, default='pending', max_length=12, verbose_name='الحالة')),
                ('done_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='المنجَز')),
                ('done_note', models.TextField(blank=True, verbose_name='ما أُنجز')),
                ('pending_note', models.TextField(blank=True, verbose_name='ما لم يُنجَز')),
                ('reported_at', models.DateTimeField(blank=True, null=True)),
                ('is_reviewed', models.BooleanField(db_index=True, default=False, verbose_name='رُوجع')),
                ('reviewed_by_person_id', models.BigIntegerField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.CharField(blank=True, max_length=255, verbose_name='ملاحظة المراجعة')),
                ('settled_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='المبلغ المعتمَد')),
                ('payroll_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('payroll_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_paid', models.BooleanField(db_index=True, default=False, verbose_name='دخل المسير')),
                ('assigned_by_employment_id', models.BigIntegerField(blank=True, null=True)),
                ('batch_key', models.CharField(blank=True, db_index=True, max_length=40)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.account', verbose_name='الحساب')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.company', verbose_name='الشركة')),
                ('employment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_activities', to='employees.employment', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'نشاط عمل',
                'verbose_name_plural': 'أنشطة العمل',
                'ordering': ['-work_date', 'id'],
                'indexes': [models.Index(fields=['employment', 'work_date'], name='idx_activity_emp_date'), models.Index(fields=['company', 'status'], name='idx_activity_company_status'), models.Index(fields=['company', 'is_reviewed', 'is_paid'], name='idx_activity_review_paid')],
                'constraints': [models.UniqueConstraint(fields=('employment', 'work_date', 'title'), name='uq_activity_emp_date_title')],
            },
        ),
    ]
