# Generated by Django 5.2.6 on 2026-09-13 09:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_builtin_roles_are_system'),
        ('employees', '0025_activities_rls'),
        ('organization', '0002_org_rls'),
    ]

    operations = [
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('code', models.CharField(max_length=40, verbose_name='الرمز')),
                ('name_ar', models.CharField(max_length=200, verbose_name='المؤشّر')),
                ('description', models.TextField(blank=True, verbose_name='التعريف')),
                ('kind', models.CharField(choices=[('quantitative', 'كمّيّ'), ('behavioral', 'سلوكيّ')], default='quantitative', max_length=15, verbose_name='النوع')),
                ('scale', models.CharField(choices=[('percent', 'نسبة مئوية'), ('scale_5', 'سُلّم من ١ إلى ٥'), ('count', 'عدد')], default='percent', max_length=12, verbose_name='المقياس')),
                ('direction', models.CharField(choices=[('higher', 'الأعلى أفضل'), ('lower', 'الأقلّ أفضل')], default='higher', max_length=10, verbose_name='الاتجاه')),
                ('unit', models.CharField(blank=True, max_length=40, verbose_name='الوحدة')),
                ('default_target', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='الهدف الافتراضيّ')),
                ('state', models.CharField(choices=[('draft', 'مسودّة'), ('pending', 'بانتظار اعتماد الموارد'), ('approved', 'معتمد'), ('rejected', 'مرفوض')], db_index=True, default='draft', max_length=12, verbose_name='الحالة')),
                ('approved_by_person_id', models.BigIntegerField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.CharField(blank=True, max_length=255)),
                ('created_by_employment_id', models.BigIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.account', verbose_name='الحساب')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.company', verbose_name='الشركة')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='organization.department', verbose_name='الإدارة')),
            ],
            options={
                'verbose_name': 'مؤشّر أداء',
                'verbose_name_plural': 'مؤشّرات الأداء',
                'ordering': ['department', 'name_ar'],
            },
        ),
        migrations.CreateModel(
            name='ReviewCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('code', models.CharField(max_length=40, verbose_name='الرمز')),
                ('name_ar', models.CharField(max_length=120, verbose_name='الدورة')),
                ('start_date', models.DateField(verbose_name='من')),
                ('end_date', models.DateField(verbose_name='إلى')),
                ('is_open', models.BooleanField(default=True, verbose_name='مفتوحة')),
                ('self_review_enabled', models.BooleanField(default=True, verbose_name='تقييم ذاتيّ')),
                ('upward_review_enabled', models.BooleanField(default=True, help_text='⚠️ مجهولٌ دائمًا — ولا يُنسب لصاحبه', verbose_name='تقييم المديرين')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.account', verbose_name='الحساب')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.company', verbose_name='الشركة')),
            ],
            options={
                'verbose_name': 'دورة تقييم',
                'verbose_name_plural': 'دورات التقييم',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='PeerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('kind', models.CharField(choices=[('self', 'تقييم ذاتيّ'), ('upward', 'تقييم المدير')], max_length=10, verbose_name='النوع')),
                ('author_fingerprint', models.CharField(blank=True, db_index=True, max_length=64)),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='التقدير من ٥')),
                ('strengths', models.TextField(blank=True, verbose_name='نقاط القوّة')),
                ('improvements', models.TextField(blank=True, verbose_name='ما يُحسَّن')),
                ('comment', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.account', verbose_name='الحساب')),
                ('author_employment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authored_reviews', to='employees.employment', verbose_name='المقيِّم')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.company', verbose_name='الشركة')),
                ('subject_employment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_reviews', to='employees.employment', verbose_name='المُقيَّم')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_reviews', to='employees.reviewcycle')),
            ],
            options={
                'verbose_name': 'تقييم',
                'verbose_name_plural': 'التقييمات',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='KPIAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('target', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='المستهدَف')),
                ('weight', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='الوزن %')),
                ('actual', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='الفعليّ')),
                ('entered_by_employment_id', models.BigIntegerField(blank=True, null=True)),
                ('entered_at', models.DateTimeField(blank=True, null=True)),
                ('entry_note', models.CharField(blank=True, max_length=255, verbose_name='ملاحظة الإدخال')),
                ('state', models.CharField(choices=[('draft', 'مسودّة'), ('pending', 'بانتظار اعتماد الموارد'), ('approved', 'معتمد'), ('rejected', 'مرفوض')], db_index=True, default='draft', max_length=12, verbose_name='الحالة')),
                ('approved_by_person_id', models.BigIntegerField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.CharField(blank=True, max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.account', verbose_name='الحساب')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.company', verbose_name='الشركة')),
                ('employment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_assignments', to='employees.employment', verbose_name='الموظف')),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='employees.kpi', verbose_name='المؤشّر')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='employees.reviewcycle', verbose_name='الدورة')),
            ],
            options={
                'verbose_name': 'إسناد مؤشّر',
                'verbose_name_plural': 'إسنادات المؤشّرات',
                'ordering': ['cycle', 'employment', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BehaviorRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='التقدير من ٥')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='ملاحظة')),
                ('rated_by_employment_id', models.BigIntegerField(blank=True, null=True)),
                ('rated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.account', verbose_name='الحساب')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.company', verbose_name='الشركة')),
                ('employment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_ratings', to='employees.employment')),
                ('kpi', models.ForeignKey(limit_choices_to={'kind': 'behavioral'}, on_delete=django.db.models.deletion.PROTECT, related_name='behavior_ratings', to='employees.kpi')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_ratings', to='employees.reviewcycle')),
            ],
            options={
                'verbose_name': 'تقدير سلوكيّ',
                'verbose_name_plural': 'التقديرات السلوكية',
            },
        ),
        migrations.AddIndex(
            model_name='kpi',
            index=models.Index(fields=['company', 'state'], name='idx_kpi_company_state'),
        ),
        migrations.AddConstraint(
            model_name='kpi',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uq_kpi_company_code'),
        ),
        migrations.AddConstraint(
            model_name='reviewcycle',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uq_cycle_company_code'),
        ),
        migrations.AddIndex(
            model_name='peerreview',
            index=models.Index(fields=['cycle', 'subject_employment', 'kind'], name='idx_peerreview_cycle_subj'),
        ),
        migrations.AddIndex(
            model_name='kpiassignment',
            index=models.Index(fields=['company', 'state'], name='idx_kpiassign_state'),
        ),
        migrations.AddIndex(
            model_name='kpiassignment',
            index=models.Index(fields=['employment', 'cycle'], name='idx_kpiassign_emp_cycle'),
        ),
        migrations.AddConstraint(
            model_name='kpiassignment',
            constraint=models.UniqueConstraint(fields=('cycle', 'employment', 'kpi'), name='uq_kpiassign_cycle_emp_kpi'),
        ),
        migrations.AddConstraint(
            model_name='behaviorrating',
            constraint=models.UniqueConstraint(fields=('cycle', 'employment', 'kpi'), name='uq_behavior_cycle_emp_kpi'),
        ),
    ]
