# Generated by Django 5.2.6 on 2026-09-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0027_performance_rls'),
    ]

    operations = [
        migrations.AddField(
            model_name='employment',
            name='training_budget_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='تغلب ميزانية الدرجة — فارغ = من الدرجة', max_digits=12, null=True, verbose_name='ميزانية التدريب'),
        ),
    ]
