# Generated by Django 5.2.6 on 2026-09-13 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0028_job_grades'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobgrade',
            name='extras',
            field=models.JSONField(blank=True, default=dict, verbose_name='مزايا إضافية'),
        ),
        migrations.AddField(
            model_name='jobgrade',
            name='training_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='ميزانية التدريب السنوية'),
        ),
    ]
