# Generated by Django 5.2.6 on 2026-09-13 12:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_builtin_roles_are_system'),
        ('employees', '0029_grade_training_budget'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('code', models.CharField(max_length=40, verbose_name='الرمز')),
                ('name_ar', models.CharField(max_length=200, verbose_name='الدورة')),
                ('provider', models.CharField(blank=True, max_length=150, verbose_name='الجهة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('duration_hours', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='المدّة (ساعة)')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='التكلفة')),
                ('delivery_mode', models.CharField(choices=[('onsite', 'حضوريّ'), ('online', 'عن بُعد'), ('hybrid', 'مدمج')], default='onsite', max_length=10, verbose_name='نمط التقديم')),
                ('is_active', models.BooleanField(default=True, verbose_name='متاحة')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.account', verbose_name='الحساب')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.company', verbose_name='الشركة')),
            ],
            options={
                'verbose_name': 'دورة تدريبية',
                'verbose_name_plural': 'الدورات التدريبية',
                'ordering': ['name_ar'],
            },
        ),
        migrations.CreateModel(
            name='TrainingNomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('scheduled_on', models.DateField(blank=True, null=True, verbose_name='موعد الدورة')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='التكلفة المحتسَبة')),
                ('state', models.CharField(choices=[('pending', 'بانتظار اعتماد الموارد'), ('approved', 'معتمد'), ('rejected', 'مرفوض'), ('attended', 'حضر'), ('no_show', 'لم يحضر'), ('cancelled', 'أُلغي')], db_index=True, default='pending', max_length=12, verbose_name='الحالة')),
                ('nominated_by_employment_id', models.BigIntegerField(blank=True, null=True)),
                ('decided_by_person_id', models.BigIntegerField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.CharField(blank=True, max_length=255, verbose_name='سبب القرار')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='الدرجة')),
                ('passed', models.BooleanField(blank=True, null=True, verbose_name='اجتاز')),
                ('certificate_url', models.CharField(blank=True, max_length=500, verbose_name='الشهادة')),
                ('completed_on', models.DateField(blank=True, null=True, verbose_name='تاريخ الإتمام')),
                ('result_note', models.CharField(blank=True, max_length=255, verbose_name='ملاحظة النتيجة')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.account', verbose_name='الحساب')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.company', verbose_name='الشركة')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nominations', to='employees.trainingcourse', verbose_name='الدورة')),
                ('employment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_nominations', to='employees.employment', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'ترشيح تدريب',
                'verbose_name_plural': 'ترشيحات التدريب',
                'ordering': ['-scheduled_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TrainingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('course_name', models.CharField(max_length=200, verbose_name='الدورة المطلوبة')),
                ('provider', models.CharField(blank=True, max_length=150, verbose_name='الجهة المقترحة')),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='التكلفة التقديرية')),
                ('justification', models.TextField(verbose_name='مبرّر الطلب')),
                ('reference_url', models.CharField(blank=True, max_length=500, verbose_name='رابط الدورة')),
                ('state', models.CharField(choices=[('pending', 'بانتظار اعتماد الموارد'), ('approved', 'معتمد'), ('rejected', 'مرفوض'), ('attended', 'حضر'), ('no_show', 'لم يحضر'), ('cancelled', 'أُلغي')], db_index=True, default='pending', max_length=12, verbose_name='الحالة')),
                ('decided_by_person_id', models.BigIntegerField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.CharField(blank=True, max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.account', verbose_name='الحساب')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.company', verbose_name='الشركة')),
                ('created_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_requests', to='employees.trainingcourse')),
                ('employment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_requests', to='employees.employment', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'طلب تدريب',
                'verbose_name_plural': 'طلبات التدريب',
                'ordering': ['-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='trainingcourse',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uq_course_company_code'),
        ),
        migrations.AddIndex(
            model_name='trainingnomination',
            index=models.Index(fields=['company', 'state'], name='idx_nomination_company_state'),
        ),
        migrations.AddIndex(
            model_name='trainingnomination',
            index=models.Index(fields=['employment', 'state'], name='idx_nomination_emp_state'),
        ),
    ]
