# Generated by Django 5.2.6 on 2026-08-30 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0010_billing_inherit_base'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(max_length=80, unique=True, verbose_name='مفتاح الحدث')),
                ('module', models.CharField(max_length=40, verbose_name='الوحدة')),
                ('name_ar', models.CharField(max_length=200, verbose_name='الاسم')),
                ('description_ar', models.TextField(blank=True, verbose_name='الوصف')),
                ('default_channels', models.JSONField(default=list, verbose_name='القنوات الافتراضية')),
                ('is_mandatory', models.BooleanField(default=False, help_text='لا يستطيع المستخدم إيقافه — أحداث حرجة', verbose_name='إلزامي')),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'حدث إشعار',
                'verbose_name_plural': 'أحداث الإشعارات',
                'ordering': ['module', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('company_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('recipient_person_id', models.BigIntegerField(db_index=True, verbose_name='المستقبل')),
                ('event_key', models.CharField(db_index=True, max_length=80)),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('body', models.TextField(blank=True, verbose_name='النص')),
                ('link_url', models.CharField(blank=True, max_length=500, verbose_name='الرابط')),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('locale', models.CharField(default='ar', max_length=5)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.account', verbose_name='الحساب')),
            ],
            options={
                'verbose_name': 'إشعار',
                'verbose_name_plural': 'الإشعارات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('channel', models.CharField(choices=[('in_app', 'داخل النظام'), ('email', 'بريد إلكتروني'), ('whatsapp', 'واتساب'), ('push', 'إشعار جوال')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'قيد الإرسال'), ('sent', 'أُرسل'), ('delivered', 'وصل'), ('failed', 'فشل'), ('skipped', 'متخطّى')], db_index=True, default='pending', max_length=20)),
                ('provider_ref', models.CharField(blank=True, max_length=120)),
                ('cost', models.DecimalField(decimal_places=4, default=0, help_text='تكلفة واتساب تُحتسب في الاستهلاك', max_digits=10)),
                ('error', models.TextField(blank=True)),
                ('attempted_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.account', verbose_name='الحساب')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='notifications.notification')),
            ],
            options={
                'verbose_name': 'تسليم إشعار',
                'verbose_name_plural': 'تسليمات الإشعارات',
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('person_id', models.BigIntegerField(db_index=True, verbose_name='الشخص')),
                ('event_key', models.CharField(max_length=80)),
                ('channel', models.CharField(choices=[('in_app', 'داخل النظام'), ('email', 'بريد إلكتروني'), ('whatsapp', 'واتساب'), ('push', 'إشعار جوال')], max_length=20)),
                ('is_enabled', models.BooleanField(default=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.account', verbose_name='الحساب')),
            ],
            options={
                'verbose_name': 'تفضيل إشعار',
                'verbose_name_plural': 'تفضيلات الإشعارات',
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('event_key', models.CharField(db_index=True, max_length=80)),
                ('channel', models.CharField(choices=[('in_app', 'داخل النظام'), ('email', 'بريد إلكتروني'), ('whatsapp', 'واتساب'), ('push', 'إشعار جوال')], max_length=20)),
                ('locale', models.CharField(choices=[('ar', 'العربية'), ('en', 'English'), ('ur', 'اردو')], max_length=5)),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='العنوان')),
                ('body', models.TextField(help_text='متغيرات بصيغة {{employee_name}}', verbose_name='النص')),
                ('account', models.ForeignKey(blank=True, help_text='فارغ = قالب افتراضي', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_templates', to='accounts.account')),
            ],
            options={
                'verbose_name': 'قالب إشعار',
                'verbose_name_plural': 'قوالب الإشعارات',
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(condition=models.Q(('read_at__isnull', True)), fields=['recipient_person_id', '-created_at'], name='idx_notif_unread'),
        ),
        migrations.AddConstraint(
            model_name='notificationpreference',
            constraint=models.UniqueConstraint(fields=('person_id', 'event_key', 'channel'), name='uq_pref_per_person'),
        ),
        migrations.AddConstraint(
            model_name='notificationtemplate',
            constraint=models.UniqueConstraint(fields=('account', 'event_key', 'channel', 'locale'), name='uq_template_per_account'),
        ),
        migrations.AddConstraint(
            model_name='notificationtemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('account__isnull', True)), fields=('event_key', 'channel', 'locale'), name='uq_default_template'),
        ),
    ]
