# Generated by Django 5.2.6 on 2026-09-08 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_invite_preview_trim'),
        ('core', '0006_storedfile_rls'),
        ('notifications', '0002_notifications_rls'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('company_id', models.BigIntegerField(db_index=True, verbose_name='الشركة')),
                ('kind', models.CharField(choices=[('general', 'إعلان عام'), ('event', 'فعالية'), ('meeting', 'اجتماع'), ('congrats', 'تهنئة'), ('condolence', 'تعزية'), ('decision', 'قرار إداري')], db_index=True, default='general', max_length=20, verbose_name='النوع')),
                ('title_ar', models.CharField(max_length=255, verbose_name='العنوان')),
                ('title_en', models.CharField(blank=True, max_length=255, verbose_name='العنوان بالإنجليزية')),
                ('body_ar', models.TextField(verbose_name='النص')),
                ('body_en', models.TextField(blank=True, verbose_name='النص بالإنجليزية')),
                ('audience_type', models.CharField(choices=[('company', 'كل الشركة'), ('departments', 'إدارات محددة'), ('persons', 'أشخاص محددون')], max_length=20, verbose_name='المستقبلون')),
                ('audience_ids', models.JSONField(blank=True, default=list, verbose_name='المحددون')),
                ('via_email', models.BooleanField(default=False, help_text='داخل النظام دائمًا، والبريد باختيار المرسل', verbose_name='إرسال بالبريد')),
                ('sent_by_person_id', models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='المرسل')),
                ('recipient_count', models.IntegerField(default=0, verbose_name='عدد المستقبلين')),
                ('sent_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='أُرسل في')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.account', verbose_name='الحساب')),
            ],
            options={
                'verbose_name': 'إعلان',
                'verbose_name_plural': 'الإعلانات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnnouncementAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.account', verbose_name='الحساب')),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='notifications.announcement')),
                ('stored_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.storedfile')),
            ],
            options={
                'verbose_name': 'مرفق إعلان',
                'verbose_name_plural': 'مرفقات الإعلانات',
            },
        ),
    ]
