# Generated by Django 5.2.6 on 2026-09-21 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0064_invite_existing_free_only'),
        ('notifications', '0004_announcements_rls'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('person_id', models.BigIntegerField(db_index=True, verbose_name='الشخص')),
                ('token', models.CharField(max_length=200, verbose_name='رمز الجهاز')),
                ('platform', models.CharField(choices=[('ios', 'آيفون'), ('android', 'أندرويد')], max_length=10, verbose_name='المنصّة')),
                ('app_version', models.CharField(blank=True, max_length=20, verbose_name='إصدار التطبيق')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='نشط')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر ظهور')),
                ('deactivated_reason', models.CharField(blank=True, max_length=120, verbose_name='سبب التعطيل')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.account', verbose_name='الحساب')),
            ],
            options={
                'verbose_name': 'جهاز جوال',
                'verbose_name_plural': 'أجهزة الجوال',
                'indexes': [models.Index(fields=['person_id', 'is_active'], name='idx_push_person_active')],
                'constraints': [models.UniqueConstraint(fields=('account', 'token'), name='uq_push_device_account_token')],
            },
        ),
    ]
